### ISSUE TITLE
提交工单功能在哪里？

### ISSUE THREAD

**Issue by jonefeewang** [welliamcao/OpsManage#10]
如题,还有审批什么的

**Comment by jonefeewang** [comment]
![image](https://user-images.githubusercontent.com/3032599/28361471-764c9308-6cab-11e7-9c80-3e8129c6ac92.png)
这个是我的生产环境功能，请问提交工单在什么地方？
另外这个项目有没有gitter聊天室？

**Comment by welliamcao** [comment]
先初始化代码，等初始化成功之后，点击play按钮，就会自动跳到，工单申请界面。

**Comment by jonefeewang** [comment]
明白了，谢谢
