### ISSUE TITLE
SQL回滚问题

### ISSUE THREAD

**Issue by pythonzm** [welliamcao/OpsManage#101]
大佬，我在SQL审核的这个功能下，如果不启动备份功能，SQL能正常运行，启动备份之后，就会有提示Invalid remote backup information.但是我的备份服务器都已经配置好了，账号和权限也都配了，也配置了binlog和server id，binlog_format设置的mixed，请问大佬还有哪些需要注意到地方么

**Comment by welliamcao** [comment]
Inception搭建了吗？
