### ISSUE TITLE
启动服务报错。。

### ISSUE THREAD

**Issue by wbamyln** [welliamcao/OpsManage#11]
[root@www01 OpsManage]# python manage.py runserver ip:8000
Performing system checks...

System check identified no issues (0 silenced).
July 22, 2017 - 22:33:29
Django version 1.8.17, using settings 'OpsManage.settings'
Starting development server at http://ip:8000/
Quit the server with CONTROL-C.
Error: [Errno -2] Name or service not known

Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address               Foreign Address             State      
tcp        0      0 127.0.0.1:6379              0.0.0.0:*                   LISTEN      
tcp        0      0 0.0.0.0:22                  0.0.0.0:*                   LISTEN      
tcp        0      0 127.0.0.1:25                0.0.0.0:*                   LISTEN      
tcp        0      0 0.0.0.0:3306                0.0.0.0:*                   LISTEN      
tcp        0      0 :::22                       :::*                        LISTEN      
tcp        0      0 ::1:25                      :::*                        LISTEN  

mysql> show tables;
+--------------------------------------------+
| Tables_in_opsmanage                        |
+--------------------------------------------+
| OpsManage_ansible_callback_model_result    |
| OpsManage_ansible_callback_playbook_result |
| auth_group                                 |
| auth_group_permissions                     |
| auth_permission                            |
| auth_user                                  |
| auth_user_groups                           |
| auth_user_user_permissions                 |
| celery_taskmeta                            |

mysql> select id,password from auth_user;
+----+-------------------------------------------------------------------------------+
| id | password                                                                      |
+----+-------------------------------------------------------------------------------+
|  1 | pbkdf2_sha256$20000$0dVCzn988kfU$vELZOB1+wHjuQNq3O2UlqvGJkqL1j1LE/BNOCQWk1vQ= |
+----+-------------------------------------------------------------------------------+
1 row in set (0.00 sec)

**Comment by welliamcao** [comment]
python manage.py runserver 192.168.1.233:8000 IP换成自己的服务器的IP
