### ISSUE TITLE
同样的密码不同的主机，本地可以ssh过去，平台上做主机信息同步，就报错

### ISSUE THREAD

**Issue by qingduyu** [welliamcao/OpsManage#110]
![image](https://user-images.githubusercontent.com/10934057/42259012-239c1256-7f91-11e8-97dd-51bb27b450f9.png)

这个报错，就是我添加了一个新主机后，同步信息发现不行，连接不上，尝试在pycharm 中追踪报错，发现追踪不到

![ghit c8v b3 t bc8v 1 7k](https://user-images.githubusercontent.com/10934057/42259037-3a9824d6-7f91-11e8-8834-689fffd6f069.png)
这个就是添加一个新主机后，能够同步信息。

**Comment by welliamcao** [comment]
已修复，详见https://github.com/welliamcao/OpsManage/commit/09d118a2959587dfdf6ecae1dd5a457ee9380458
