### ISSUE TITLE
【Ansible模块管理】sudo 账户提示需要密码，实际已经配置了密码，并且密码验证无问题。

### ISSUE THREAD

**Issue by samesky2016** [welliamcao/OpsManage#112]
问题描述：
1、在Ansible模块管理执行shell命令时，提示提示需要密码，实际已经配置了密码，并且密码验证无问题。
2、使用root账户，则无上述问题。
注：此问题在更新主体信息时也是同样提示：数据更新失败-请检查Ansible配置

Ansible模块管理，报错信息如下：
10.10.203.10 | FAILED | rc=1 >> 
sudo: a password is required

**Comment by welliamcao** [comment]
已修复，详见https://github.com/welliamcao/OpsManage/commit/39b333f19624427691fc05507020284a4d45eccb

**Comment by samesky2016** [comment]
已经拉取最新代码验证，问题已经修复，感谢！~
