### ISSUE TITLE
【关于需求】能否在资产列表中增加一列为”备注” 方便用户新增服务器或虚拟机时能够备注此服务器的用途（例如部署的是什么服务、部署的路径等）

### ISSUE THREAD

**Issue by samesky2016** [welliamcao/OpsManage#113]
1、提一个需求：
【关于需求】能否在资产列表中增加一列为”备注” 方便用户新增服务器或虚拟机时能够备注此服务器的用途（例如部署的是什么服务、部署的路径等）

**Comment by welliamcao** [comment]
已添加了资产备注功能，更新代码之后，执行SQL
`ALTER TABLE `opsmanage_assets` ADD `mark` text NULL comment '资产备注';`

**Comment by samesky2016** [comment]
刚才验证了一下，已经有备注栏了，感谢！
另，前端还有点问题，麻烦改下：
问题描述：
1、在备注栏，如果输入内容时如有回车换行则会报如下错误，
SyntaxError: Invalid or unexpected token

**Comment by welliamcao** [comment]
不能使用换行，js不支持换行的字符串拼接。%>_<%

**Comment by samesky2016** [comment]
关于这个问题，我改了一下assets_modf.html 中的一个js函数，已经解决此问题，看是否可以采纳合并到代码中去。
改动如下：
function getFormData (form, filler) {
	var assets = {};
	var server = {};
	var net = {};
	for (var i = 0; i < form.length; ++i) {
		var name = form[i].name;
		var value = form[i].value;
		if (name.length == 0)
			continue;
		 
		**value  = value.replace(/\n/g,'<br/>');** //替换掉换行符。

**Comment by welliamcao** [comment]
已修改，详见https://github.com/welliamcao/OpsManage/commit/9ca7471ed17e03a467167eca97881f698f79bb0e
