### ISSUE TITLE
【内存计算不一致问题】点开详情栏中“+“”按钮，展示的内存和操作栏中“查看详细信息”中展示内存不一致。

### ISSUE THREAD

**Issue by samesky2016** [welliamcao/OpsManage#114]
【重现步骤】
1、点开详情栏中的按钮查看内存大小；
2、点开操作栏中“查看详细按钮”检查内存大小；
【结果】
连个地方内存大小展示不一致，
【期望】
详情中展示4G（电脑实际内存4G）

----------------分割线-------------------------
详情栏：

CPU型号: | Intel(R) Xeon(R) CPU E5-2682 v4 2.50GHz
-- | --
CPU个数: | 2
硬盘容量: | 80GB
内存容量: | 3GB

操作栏：
内存容量：3832MB

**Comment by welliamcao** [comment]
计算方式不一致，稍后统一下计算方法。

**Comment by samesky2016** [comment]
验证已修复!
