### ISSUE TITLE
【建议】应用部署--》运行模块、在线添加执行脚本过程中，执行结果的窗口建议固定，内部设置滚动条或是设置只显示最新多少条

### ISSUE THREAD

**Issue by samesky2016** [welliamcao/OpsManage#115]
【建议】应用部署--》运行模块、在线添加模块执行脚本过程中，执行结果的窗口建议固定，内部设置滚动条或是设置只显示最新多少条（例如30条）执行纪律

**Comment by welliamcao** [comment]
这个暂时不考虑了，之前就是固定位置的后来又要求改成自动到底部，实在有点众口难调。
