### ISSUE TITLE
【在线添加】sudo执行脚本时，会报10.10.203.176 | FAILED | rc=1 >>  sudo: a password is required

### ISSUE THREAD

**Issue by samesky2016** [welliamcao/OpsManage#116]
【在线添加】sudo执行脚本时(密码确认正确)，会报10.10.203.176 | FAILED | rc=1 >>  sudo: a password is required

**Comment by welliamcao** [comment]
已修复，详见https://github.com/welliamcao/OpsManage/commit/8ff3729603480164397a83d692c7749fe09c114c

**Comment by samesky2016** [comment]
验证已修复!
