### ISSUE TITLE
【项目部署】点击确认部署，提示无权限（有提供sudo权限）。

### ISSUE THREAD

**Issue by samesky2016** [welliamcao/OpsManage#117]
Permission denied, please try again. Permission denied,
 please try again. Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password). 
rsync: connection unexpectedly closed (0 bytes received so far) 
[sender] rsync error: unexplained error (code 255) at io.c(600) [sender=3.0.6]

**Comment by welliamcao** [comment]
代码部署，服务器认证模式只能用证书模式。
