### ISSUE TITLE
1146, "Table 'opsmanage.opsmanage_order_system' doesn't exist"

### ISSUE THREAD

**Issue by yslhzj** [welliamcao/OpsManage#119]
你好, 登陆认证完成后,出现这个问题.
Request Method: | GET
-- | --
http://100.76.37.18:8000/user/center/
1.11.7
ProgrammingError
(1146, "Table 'opsmanage.opsmanage_order_system' doesn't exist")

![image](https://user-images.githubusercontent.com/29890756/42671357-2881e16c-8692-11e8-9313-9be8e7e7c215.png)

**Comment by welliamcao** [comment]
部署文档第八部没有做。
```
# cd /mnt/OpsManage/
# python manage.py makemigrations OpsManage
# python manage.py makemigrations wiki
# python manage.py makemigrations orders
# python manage.py makemigrations filemanage
# python manage.py migrate
# python manage.py createsuperuser
```
