### ISSUE TITLE
ansble部署应用的时候，如果服务器端口不是22，该如何配置？

### ISSUE THREAD

**Issue by Tgkplvfy** [welliamcao/OpsManage#120]
添加资产的时候端口有正确填写。

执行模块的时候：
[Start] Ansible Model: ping  ARGS:

192.168.1.56 | UNREACHABLE! => {
    **"msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.1.56 port 22: Connection refused\r\n", 
    "unreachable": true**
}

[Done] Ansible Done.

在服务器上用ansible 192.168.1.56 -m ping 是可以执行的。

**Comment by welliamcao** [comment]
按照我这个执行一下，看一下结果：
```msg="host:{{ inventory_hostname }} ,port:{{ ansible_ssh_port }}"```
![image](https://user-images.githubusercontent.com/5885314/42758319-b45163ca-8935-11e8-9b05-11fda69d2631.png)
