### ISSUE TITLE
又来提bug了，发布日志页面删除日志报404，发现api有问题

### ISSUE THREAD

**Issue by blueiq** [welliamcao/OpsManage#122]
又来提bug了，发布日志页面删除日志报404，api有问题，/api/logs/deploy与/api/deploy是一样的。

**Comment by welliamcao** [comment]
收到，下次提交更新。

**Comment by welliamcao** [comment]
已修复，详见https://github.com/welliamcao/OpsManage/commit/20cacce73a7be31e1db8ece49ac38d547cf4447a
