### ISSUE TITLE
灰度发布以及代码发布前的操作

### ISSUE THREAD

**Issue by xiaogangfighting** [welliamcao/OpsManage#132]
1、"代码发布"  这个为啥没有"部署前的操作"，比如我会停掉tomcat
2、灰度发布 怎么做呢？
3、代码发布以及回滚都是软链接方式么？

**Comment by welliamcao** [comment]
1、没有。
2、添加代码发布的时候可以选择一批服务器，部署跟生产环境一样的代码就行了，灰度测试通过就可以部署到生产环境。
3、回滚是以软连接的方式。

**Comment by huanzui** [comment]
> 1、没有。
> 2、添加代码发布的时候可以选择一批服务器，部署跟生产环境一样的代码就行了，灰度测试通过就可以部署到生产环境。
> 3、回滚是以软连接的方式。

请问一下程序发布选择的gitlab地址时，怎么填写获取代码的用户名密码或token?
