### ISSUE TITLE
关于将python2.7和django1.11替换成python3.6+和django2.x

### ISSUE THREAD

**Issue by waydeng** [welliamcao/OpsManage#133]
我想尝试一下把项目里的python版本和django版本替换成一个新的版本，是否有些功能或者模块会在python3里面或者django2.x+里面无法实现？

**Comment by welliamcao** [comment]
欢迎，不过我也没试过django 2.x。最新在开发3.0，前端跟后端基本上重写了%>_<%

**Comment by phaibin** [comment]
@welliamcao 3.0会是前后端分离的么？有计划何时完成么？

**Comment by welliamcao** [comment]
@phaibin 90%分离，希望春节前能发布吧

**Comment by fycsq** [comment]
@welliamcao 
作者考虑集成ZABBIX之类的监控管理功能吗？
