### ISSUE TITLE
全局开启日志，各个模块都没有日志记录

### ISSUE THREAD

**Issue by zhangsj** [welliamcao/OpsManage#138]
全局开启日志，各个模块都没有日志记录

**Comment by welliamcao** [comment]
看一下Celery是不是挂掉了

**Comment by zhangsj** [comment]
celery 正常，其他功能都也是正常的
celery-beat                      RUNNING   pid 2512, uptime 1 day, 4:52:20
celery-cam                       RUNNING   pid 2071, uptime 1 day, 20:37:12
celery-worker-ansible            RUNNING   pid 1953, uptime 1 day, 20:38:58
celery-worker-default            RUNNING   pid 1952, uptime 1 day, 20:38:58

**Comment by welliamcao** [comment]
先用supervisor把celery进程全部关掉，在杀掉服务器上的celery进程。最后再用supervisor重新启动。

**Comment by zhangsj** [comment]
ok  非常感谢

**Comment by haiya512** [comment]
@welliamcao 

1. 你所有的日志入库是不是都是通过celery来做的？

2. 有没有用其他方法？

3. 以后有这个打算吗？
