### ISSUE TITLE
settings.py脚本内相关问题

### ISSUE THREAD

**Issue by flylove114** [welliamcao/OpsManage#14]
我想问下settings.py中的你定义的redis  的这个参数BROKER_URL = 'redis://121.199.26.4:6379/3'   端口号后面的3是什么意思？（你redis创建好后需要创建key吗？）还有我启动你下面的异步Celery ，但是追加的日志中总是报无法连接ERROR/MainProcess] consumer: Cannot connect to redis://121.199.26.4:6379/3: .
Trying again in 32.00 seconds... （尝试安装rabbitmq也无果）

**Comment by welliamcao** [comment]
3代表的redis db3，第三个数据库。redis默认是16个数据库

**Comment by flylove114** [comment]
那这数据库需要我手动创建吗？

**Comment by welliamcao** [comment]
例外建议公网环境，在没有配置认证的情况下不要暴露redis

**Comment by welliamcao** [comment]
不需要手动创建，默认就有

**Comment by flylove114** [comment]
那我上面那个异步Celery启动后，一直报ERROR/MainProcess] consumer: Cannot connect to redis://121.199.26.4:6379/3: .
Trying again in 32.00 seconds... ，这块主要是什么问题呢

**Comment by welliamcao** [comment]
telnet访问你的redis正常吗？

**Comment by flylove114** [comment]
恩，这个正常的

**Comment by welliamcao** [comment]
你的telnet测试命令是什么？

**Comment by flylove114** [comment]
telnet 121.199.26.4 6379

**Comment by flylove114** [comment]
你好，你使用在线软件吗（比如QQ）方便加下沟通下，不胜感激（我的QQ：940612339）

**Comment by welliamcao** [comment]
303350019，不过我一般晚上才有空，回复信息。

**Comment by flylove114** [comment]
恩，加你了谢谢
