### ISSUE TITLE
1，工单申请，上线sql不能选到执行人。2，用户管理中心，用户和用户有什么关联

### ISSUE THREAD

**Issue by liangjsbfy** [welliamcao/OpsManage#142]
![1](https://user-images.githubusercontent.com/43529723/48828017-a4816700-eda9-11e8-83f5-7aa0eb87fbd9.jpg)

**Comment by liangjsbfy** [comment]
不行呢。
我看审核组的用户是在资产里拿的，而且那里的组成员和用户管理里的用户没关系
![2](https://user-images.githubusercontent.com/43529723/48891503-7d449b80-ee76-11e8-8840-e429d126b87e.jpg)
![3](https://user-images.githubusercontent.com/43529723/48891552-9cdbc400-ee76-11e8-8ede-0ca4379f4b1d.jpg)
![4](https://user-images.githubusercontent.com/43529723/48891558-a36a3b80-ee76-11e8-94a7-ac400d0182f8.jpg)

**Comment by welliamcao** [comment]
你的DBA跟ROOT组，里面有成员吗？成员不包括自己。

**Comment by liangjsbfy** [comment]
在哪里往组加入成员？

**Comment by welliamcao** [comment]
用户管理菜单栏

**Comment by liangjsbfy** [comment]
没有看到该功能

![5](https://user-images.githubusercontent.com/43529723/48892565-5340a880-ee79-11e8-8367-2d2560317f5f.jpg)
![6](https://user-images.githubusercontent.com/43529723/48892616-6eabb380-ee79-11e8-9842-972d52113254.jpg)
![7](https://user-images.githubusercontent.com/43529723/48892630-7a977580-ee79-11e8-9531-432d8681619e.jpg)

**Comment by welliamcao** [comment]
![image](https://user-images.githubusercontent.com/5885314/48892931-22ad3e80-ee7a-11e8-8ce9-26891234f20d.png)
你点这个账户进去，不能分配组吗o(╥﹏╥)o

**Comment by liangjsbfy** [comment]
![image](https://user-images.githubusercontent.com/43529723/48893065-64d68000-ee7a-11e8-858e-f916e2065f45.png)
原来那里可以点啊！！
新增用户的时候，能否指定组，并且可以修改用户的信息？

**Comment by liangjsbfy** [comment]
![image](https://user-images.githubusercontent.com/43529723/48893261-eb8b5d00-ee7a-11e8-945e-224627e8fb5e.png)

**Comment by welliamcao** [comment]
这个没必要了吧，功能重复了~

**Comment by welliamcao** [comment]
issues可以关闭了吗？ @liangjsbfy
