### ISSUE TITLE
添加资产和运行模块相关问题

### ISSUE THREAD

**Issue by flylove114** [welliamcao/OpsManage#15]
我这边搭建好后，每次添加资产，都会提示我数据格式不对（使用的是账户密码模式，我密码也没特殊符号，8位数）还有个问题添加资产错误，但是点击后还是能添加上去，然后我运行应用部署里面的运行模块
使用shell uptime命令，然后执行结果就是一直在执行中，无结果，不知道什么问题，麻烦解答下？
![110](https://user-images.githubusercontent.com/30486271/28653235-0907b790-72bf-11e7-8854-eaa84a60db87.png)
![114](https://user-images.githubusercontent.com/30486271/28653238-0d88c30e-72bf-11e7-8560-a628cf3d106f.png)

**Comment by welliamcao** [comment]
用浏览器审查元素，看一下respone返回的具体内容

**Comment by flylove114** [comment]
返回500
![112](https://user-images.githubusercontent.com/30486271/28653554-c3e23c06-72c0-11e7-9285-954b18fdeffd.png)

**Comment by flylove114** [comment]
看好像是没请求到这个data
![113](https://user-images.githubusercontent.com/30486271/28653610-08f4a20c-72c1-11e7-89f7-05d628ae2ebe.png)

**Comment by flylove114** [comment]
![115](https://user-images.githubusercontent.com/30486271/28653621-1d31ae54-72c1-11e7-91d0-7b8e2d2c91df.png)
