### ISSUE TITLE
文件丢失疑问

### ISSUE THREAD

**Issue by yangyang198599** [welliamcao/OpsManage#151]
centos7.5 
mysql 5.7

项目部署在/opt/目录下
bug--流程---
功能使用都正常，除了wiki列表，修改了 "select id, date_formate(created_time,'%%Y-%%m')......" 后使用没有问题
打开代码部署，编辑shell部署脚本 mvn clean package 。。。。。

选择部署报错。回看、opt目录，文件全部被删除 重试了两次，都是这样，项目也被删除

**Comment by welliamcao** [comment]
新版本已经改了部署方式，issues关闭
