### ISSUE TITLE
资产管理的疑问

### ISSUE THREAD

**Issue by myselfghost** [welliamcao/OpsManage#16]
1资产管理部分，是否支持自定义属性（或叫字段）？
2不提供批量导入或者接口操作吗？

**Comment by welliamcao** [comment]
第一点是什么意思？第二个企业定制版有这个功能能，开源版本没这个功能。

**Comment by myselfghost** [comment]
每个单位关注的资产信息都不一样，所以资产的那些信息字段，自定义更改或添加什么的

**Comment by welliamcao** [comment]
需要定制，不支持自定义。

**Comment by myselfghost** [comment]
O(∩_∩)O谢谢
