### ISSUE TITLE
表字段中含有中文，回滚语句在备份数据库中正常，但在web平台中显示异常，导致回滚失败

### ISSUE THREAD

**Issue by lsp201811** [welliamcao/OpsManage#161]
数据库中的表含有中文字段，在平台执行更新语句，执行正常，备份正常，但web界面回滚语句中字段中的中文全部显示为一连串问号，但在inception备份的数据库中的显示都是正常的
例如：web 平台显示如下（只粘贴了一部分）
UPDATE `test`.`bc_shop` SET id=6,business_district_id=7,business_district_name='???????',province='43',province_name='??',city='430100000000',city_name='???',area='430104000000',area_name='???',status=1,longitude='112.935370',latitude='28.218320',range=3000,create_time='2017-11-20 16:47:17',update_time='2019-02-26 14:41:52',
上述的business_district_name等字段回滚语句全部异常

但在inception备份库中显示如下（显示正常）：
rollback_statement: UPDATE `test`.`bc_shop` SET id=6,business_district_id=7,business_district_name='长沙步步高广场',province='43',province_name='湖南',city='430100000000',city_name='长沙市',area='430104000000',area_name='岳麓区',status=1,longitude='112.935370',latitude='28.218320',range=3000,create_time='2017-11-20 16:47:17',update_time='2019-02-26 14:41:52',is_delete=0,

**Comment by welliamcao** [comment]
已解决
