### ISSUE TITLE
[BUG]筛选资产后修改信息，路由跳转问题

### ISSUE THREAD

**Issue by Lyuke-liu** [welliamcao/OpsManage#166]
由[CMDB]-[资产列表]菜单进入后，进行资产组合查询，得到筛选结果并点击
![image](https://user-images.githubusercontent.com/24935256/54339050-a62fad00-466e-11e9-9a83-f9b35120f8fe.png)

路由跳转到assets/add/?id=X 而不是正确的/assets/manage/?id=X&model=edit
![image](https://user-images.githubusercontent.com/24935256/54339171-fc045500-466e-11e9-8c78-bd157f909470.png)

**Comment by welliamcao** [comment]
> 由[CMDB]-[资产列表]菜单进入后，进行资产组合查询，得到筛选结果并点击
> ![image](https://user-images.githubusercontent.com/24935256/54339050-a62fad00-466e-11e9-9a83-f9b35120f8fe.png)
> 
> 路由跳转到assets/add/?id=X 而不是正确的/assets/manage/?id=X&model=edit
> ![image](https://user-images.githubusercontent.com/24935256/54339171-fc045500-466e-11e9-8c78-bd157f909470.png)

已修复了https://github.com/welliamcao/OpsManage/commit/a7df38680b51ff295a9cfbcdd60dc51c3ac73701
