### ISSUE TITLE
下载获取不到文件

### ISSUE THREAD

**Issue by zhangsj** [welliamcao/OpsManage#169]
![image](https://user-images.githubusercontent.com/7639036/54527829-0d729780-49b6-11e9-974b-051b2678e5b9.png)
![image](https://user-images.githubusercontent.com/7639036/54527937-5d515e80-49b6-11e9-969c-fb0d40d0b198.png)
有时目录的文件也显示不全

**Comment by zhangsj** [comment]
![image](https://user-images.githubusercontent.com/7639036/54582650-7e648e80-4a4c-11e9-9aef-89e5de20fcbc.png)
这里需要改成0

**Comment by welliamcao** [comment]
下次提交修复

**Comment by zhangsj** [comment]
但是文件超过300M下载就会报错，直接通过fetch执行报内存错误，这个问题怎么解决

**Comment by welliamcao** [comment]
你的机器多大内存？

**Comment by zhangsj** [comment]
8GB
