### ISSUE TITLE
发布代码前端页面无报错，日志有报错

### ISSUE THREAD

**Issue by zhangsj** [welliamcao/OpsManage#175]
可发布成功，但opsmanage日志有报错
![image](https://user-images.githubusercontent.com/7639036/57285499-eac34c00-70e5-11e9-9287-15d54a791ddd.png)

**Comment by welliamcao** [comment]
Nginx+Daphne+Django架构部署的？

**Comment by zhangsj** [comment]
阿里云的slb直接tcp转发到django的8000端口

**Comment by welliamcao** [comment]
服务器什么配置？redis正常吗？

**Comment by zhangsj** [comment]
服务器2C8G  redis 4.0  无明显压力

**Comment by welliamcao** [comment]
redis换成3.x，没试过4.0的
