### ISSUE TITLE
python manage.py runserver 0.0.0.0:8000运行页面后不能关闭控制台

### ISSUE THREAD

**Issue by huanzui** [welliamcao/OpsManage#179]
请教下 python manage.py runserver 0.0.0.0:8000 运行页面后不能关闭控制台，页面有后台运行的么，或随机启动的怎么做

**Comment by welliamcao** [comment]
用supervisor管理Django进程

**Comment by huanzui** [comment]
> 用supervisor管理Django进程
好的
