### ISSUE TITLE
通过zabbix api拉取zabbix里面的服务器资源列表信息

### ISSUE THREAD

**Issue by huanzui** [welliamcao/OpsManage#180]
现在功能很强大了，赞一个
能通过zabbix api拉取zabbix里面的服务器资源列表信息么？ 
资产现在只能通过导入方式

**Comment by welliamcao** [comment]
> 现在功能很强大了，赞一个
> 能通过zabbix api拉取zabbix里面的服务器资源列表信息么？
> 资产现在只能通过导入方式

可以，不过要自己开发~
