### ISSUE TITLE
v3版本的代码发布添加不了

### ISSUE THREAD

**Issue by czxin788** [welliamcao/OpsManage#181]
![image](https://user-images.githubusercontent.com/13861904/59105166-efd61e00-8965-11e9-83ea-4a5a0062d505.png)
添加项目部署失败: invalid literal for int() with base 10: 'undefined'

**Comment by czxin788** [comment]
另外，建议代码发布添加一个部署之前执行的命令的功能，这样在部署代码前，可以执行一些命令，比如先关服务，先备份等

**Comment by welliamcao** [comment]
> 另外，建议代码发布添加一个部署之前执行的命令的功能，这样在部署代码前，可以执行一些命令，比如先关服务，先备份等

最新的代码已经添加了，不过取消了对SVN的支持
