### ISSUE TITLE
V3 binglog解析失败

### ISSUE THREAD

**Issue by kevinqht** [welliamcao/OpsManage#184]
2019-06-13 16:18:18 [ERROR] database.py[line:418] binglog解析失败: 'utf-8' codec can't decode byte 0x92 in position 0: invalid start byte

**Comment by welliamcao** [comment]
本地测试没发现这个问题，怎么复现呢？

**Comment by kevinqht** [comment]
--谢谢回复
就是数据库管理->binlog解析->选择数据库->选择binlog  ，解析。等待好久没解析出来，最后看输出的日志就是我上面贴出来的错误。我的数据库编码是utf8mb4的，不知道与这个有没有关系。我单独使用binlog2sql拿个工具解析我数据库的binlog是没有问题的。
还有我的python版本是3.6.8的

**Comment by kevinqht** [comment]
好像binlog时间段的选择框也有点问题，选择好的时间，点确定就变了。那个框的布局可以稍微调整下，可以显示完整的时间段

**Comment by welliamcao** [comment]
> --谢谢回复
> 就是数据库管理->binlog解析->选择数据库->选择binlog ，解析。等待好久没解析出来，最后看输出的日志就是我上面贴出来的错误。我的数据库编码是utf8mb4的，不知道与这个有没有关系。我单独使用binlog2sql拿个工具解析我数据库的binlog是没有问题的。
> 还有我的python版本是3.6.8的

那就可以能是数据库编码问题，代码里面指定的是utf8的

**Comment by kevinqht** [comment]
确实是编码的问题，utf8mb4编码的数据库有不能识别的字符，加了errors='ignore'，出结果了，但是准确性没法保障了
with open(filename, "rt", encoding='utf-8', errors='ignore') as f_tmp
同时建议作者能细化这一块，能够提供表级别的细粒度筛选

**Comment by welliamcao** [comment]
> 确实是编码的问题，utf8mb4编码的数据库有不能识别的字符，加了errors='ignore'，出结果了，但是准确性没法保障了
> with open(filename, "rt", encoding='utf-8', errors='ignore') as f_tmp
> 同时建议作者能细化这一块，能够提供表级别的细粒度筛选

刚刚更新了功能支持了表级别的筛选
