### ISSUE TITLE
工单申请，文件分发 下载 授权人为空，不知道在哪添加

### ISSUE THREAD

**Issue by huanzui** [welliamcao/OpsManage#187]
V3版本

用户中心已添加另一个用户zhangsan，已分配了所有资产和所有操作权限

但在工单申请，文件分发 下载 下拉选择授权人为空，不知道在哪添加，V2版本可以点击人员进行操作，V3即使给了所有权限 仍为空，请问V3版本怎么弄

SQL上线标签中 即使给了所有权限 选择了对应主机 执行人 也是一样 为空。

![image](https://user-images.githubusercontent.com/7300261/60705015-a06d1880-9f38-11e9-9926-cc33fd202e91.png)

**Comment by welliamcao** [comment]
工单列表-点击按钮进行配置
![image](https://user-images.githubusercontent.com/5885314/60749765-55ebaa80-9fd1-11e9-8e1b-a789e707c819.png)

**Comment by huanzui** [comment]
终于看到了，不说还真不知道这个功能，谢谢
