### ISSUE TITLE
v3 界面问题

### ISSUE THREAD

**Issue by justbaibai** [welliamcao/OpsManage#188]
安照安装步骤 安装的  除了这个报错
App 'apps' could not be found. Is it in INSTALLED_APPS?
之后进入页面右上角的管理员选项除了logout 别的都不好使（help set profile都不好使）
和刚进页面出现失败  和有历史数据 这正常么 刚接触请解答一下
我用的是谷歌游览器
![问题1](https://user-images.githubusercontent.com/20961309/61097781-259f8280-a48f-11e9-8779-95777269d43d.JPG)

**Comment by welliamcao** [comment]
```
/usr/local/python3/bin/python3 manage.py makemigrations cicd
 /usr/local/python3/bin/python3 manage.py migrate
```
部署文档里面有误，执行一下上面这俩个命令。那个数据不是历史数据是假数据，平台有真实数据时会替换掉。
