### ISSUE TITLE
svn部署报错

### ISSUE THREAD

**Issue by zhixingchou** [welliamcao/OpsManage#19]
初始化后，点击部署到部署服务器-版本选择，没有可以选择版本。点击确认部署报错：（错误，请注意必填项不能为空）

**Comment by welliamcao** [comment]
项目目录里面，使用命令svn log -l 10 -q能返回数据吗？

**Comment by zhixingchou** [comment]
执行命令有数据

**Comment by zhixingchou** [comment]
@welliamcao 任务管理-添加任务，测试了下定时执行命令，在客户端不会执行命令呢？

**Comment by welliamcao** [comment]
看一下客户端cron有没有报错，尽量提供详细的错误信息。

**Comment by zhixingchou** [comment]
@welliamcao 在docker安装的，使用docker的容器的客户端测试，不能执行crontab命令。

**Comment by zhixingchou** [comment]
@welliamcao docker容器python2.6升级到python2.7后，执行剧本报错：
`fatal: [172.17.0.8]: FAILED! => {"msg": "One or more items failed", "failed": true, "changed": false, "results": [{"_ansible_parsed": false, "_ansible_no_log": false, "item": ["pcre", "pcre-devel", "gcc", "gcc-c++", "autoconf", "libjpeg", "libjpeg-devel", "libpng", "libpng-devel", "freetype", "freetype-devel", "libxml2", "libxml2-devel", "zlib", "zlib-devel", "glibc", "glibc-devel", "glib2", "glib2-devel", "bzip2", "bzip2-devel", "ncurses", "ncurses-devel", "curl", "curl-devel", "libidn", "libidn-devel", "openssl", "openssl-devel", "make"], "module_stderr": "Shared connection to 172.17.0.8 closed.\r\n", "_ansible_item_result": true, "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_H9sAVd/ansible_module_yum.py\", line 25, in \r\n    import yum\r\nImportError: No module named yum\r\n", "failed": true, "invocation": {"module_name": "yum"}, "msg": "MODULE FAILURE"}]}`

**Comment by welliamcao** [comment]
@zhixingchou 客户端用虚拟机或者真实服务器做测试吧，容器化的客户端是精简版的操作系统，很多东西不支持。

**Comment by zhixingchou** [comment]
@welliamcao svn不能部署
#[http://i.imgur.com/yXlLnu8.png](url)

**Comment by welliamcao** [comment]
@zhixingchou 看上去是不能获取版本列表，要做代码断点debug看一下，你加我QQ：303350019，我远程帮你看一下。

**Comment by zhixingchou** [comment]
`前端活获取svn版本就是用的svn log这个命令，但是要需要输入用户密码。所以一直卡在哪里，前端获取不到
`
`你到项目下面手动输入这个命令，会保存账户密码信息，所以平台再次调用的时候，就不会提示要输入用户名密码了`
