### ISSUE TITLE
V3 数据库连接问题

### ISSUE THREAD

**Issue by justbaibai** [welliamcao/OpsManage#190]
![test1](https://user-images.githubusercontent.com/20961309/61193696-aeb4f480-a6ef-11e9-918c-31b6ff5baae6.JPG)
![test2](https://user-images.githubusercontent.com/20961309/61193708-ba082000-a6ef-11e9-9d24-60bfc8d0abf6.JPG)
![test3](https://user-images.githubusercontent.com/20961309/61193722-c42a1e80-a6ef-11e9-8cd2-681f8ddfa0fb.JPG)
![test34](https://user-images.githubusercontent.com/20961309/61193723-c8eed280-a6ef-11e9-82ab-6f4ae353c163.JPG)
数据库可以远程登录 授权是all 可登录ip是% 但cmdb前台报错显示是连接被拒绝 连接本地的自己的库opsmanage 也是显示被拒绝

**Comment by welliamcao** [comment]
这个入口不支持show、desc 这种命令

**Comment by justbaibai** [comment]
建议出个简单的操作手册 虽然界面基本上都通俗易懂  最好给个范例 嘻嘻
