### ISSUE TITLE
ImportError: cannot import name 'python_2_unicode_compatible'

### ISSUE THREAD

**Issue by haiya512** [welliamcao/OpsManage#192]
File "/usr/local/py37/lib/python3.7/site-packages/django_celery_beat/models.py", line 12, in <module>
    from celery.five import python_2_unicode_compatible
ImportError: cannot import name 'python_2_unicode_compatible' from 'celery.five' (/usr/local/py37/lib/python3.7/site-packages/celery/five.py)

**Comment by haiya512** [comment]
already forgot how to repeat this problem, keep it openning

**Comment by welliamcao** [comment]
pip3 freeze|grep django-celery
看一下版本

**Comment by haiya512** [comment]
> pip3 freeze|grep django-celery
> 看一下版本

没啥问题了，关闭了
