### ISSUE TITLE
0: 'ace' is not defined

### ISSUE THREAD

**Issue by MaxGaius** [welliamcao/OpsManage#195]
在国外加载不了ace呀 无法使用哦!!!!

**Comment by MaxGaius** [comment]
![image](https://user-images.githubusercontent.com/51019831/61694757-b9f9c700-ad64-11e9-90c4-c7cdc0d4a7f9.png)

**Comment by MaxGaius** [comment]
@welliamcao 希望改成本地的吧

**Comment by welliamcao** [comment]
已改成本地资源。详见：https://github.com/welliamcao/OpsManage/commit/46cc59cadb073323856f4c3052043ba9bf54e9e8
