### ISSUE TITLE
stronger

### ISSUE THREAD

**Issue by kinbod** [welliamcao/OpsManage#201]
qiang da

**Comment by kinbod** [comment]
很好，很强大啊支持

**Comment by kinbod** [comment]
能支持mysql8吗

**Comment by welliamcao** [comment]
> 能支持mysql8吗

没试过，不过api应该能通用

**Comment by kinbod** [comment]
Ok,我这边试试，谢谢

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: William.Cao <notifications@github.com>
发送时间: Friday, August 2, 2019 11:52:47 AM
收件人: welliamcao/OpsManage <OpsManage@noreply.github.com>
抄送: Bodkin Quan <carlquan@outlook.com>; Author <author@noreply.github.com>
主题: Re: [welliamcao/OpsManage] stronger (#201)


能支持mysql8吗

没试过，不过api应该能通用

―
