### ISSUE TITLE
密钥登录

### ISSUE THREAD

**Issue by yuynagforhacker** [welliamcao/OpsManage#202]
您好，我在资产界面资产列表中不存储密码，并不想用托管密码的方式使用ansible，我在服务器已经配置好了ansible免密钥登录，但是在web上执行还是用的密码登录，我应该修改哪个文件？修改哪块?

**Comment by yuynagforhacker** [comment]
还有添加资产在选择密钥登录的时候没有选择密钥，如何通过密钥登录？

**Comment by welliamcao** [comment]
你使用普通用户运行的opsmanage还是root用户

**Comment by yuynagforhacker** [comment]
以普通用户运行

**Comment by yuynagforhacker** [comment]
与启动用户身份有关吗？以www用户启动，是否因为www无法读取到密钥文件？ @welliamcao

**Comment by welliamcao** [comment]
> 与启动用户身份有关吗？以www用户启动，是否因为www无法读取到密钥文件？ @welliamcao

是的，我改一下代码兼容一下。

**Comment by yuynagforhacker** [comment]
按照您的修改方式改了代码，还是会存在那个问题，不知道是不是由于之前自己做过改动的原因，但是使用root起确实可以解决此问题，代码中在哪里声明了密钥文件路径？通过变更权限是否也可以解决此问题？  @welliamcao

**Comment by yuynagforhacker** [comment]
已调试好，感谢
