### ISSUE TITLE
这个版本问题搞死人

### ISSUE THREAD

**Issue by lrm929** [welliamcao/OpsManage#213]
![image](https://user-images.githubusercontent.com/13100167/63675882-61629180-c81c-11e9-9b88-559aea473c1b.png)

**Comment by welliamcao** [comment]
这个不是错误

**Comment by lrm929** [comment]
这个问题怎么解决呢？




| |
Mz
|
|
邮箱：lrm929@163.com
|

Signature is customized by Netease Mail Master

在2019年08月27日 11:53，William.Cao 写道：

这个不是错误

**Comment by welliamcao** [comment]
不用解决，忽略就行了

**Comment by lrm929** [comment]
同步数据都报错找不到模块，但是安装这个模块就报上面的版本不兼容问题，
![image](https://user-images.githubusercontent.com/13100167/63746468-7b14df00-c8d7-11e9-852c-da72642b83d5.png)
![Uploading image.png…]()

**Comment by lrm929** [comment]
![Uploading image.png…]()

**Comment by lrm929** [comment]
![Uploading image.png…]()
