### ISSUE TITLE
关于docker部署后数据库连接问题

### ISSUE THREAD

**Issue by Sai-kk** [welliamcao/OpsManage#215]
你好，我按照docker的教程搭建后，发现数据库的连接一直报错，
ERROR 1045 (28000): Access denied for user 'opsmanage'@'172.18.0.5' (using password: YES)

**Comment by welliamcao** [comment]
数据库配置错了，贴一下你的docker-compose.yml。

**Comment by Sai-kk** [comment]
你好，下面是我的docker-composer.yml的配置，应该和redis和rabbitmq没关系就没帖上来
services:
  db:
    image: mysql:5.6  
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_DATABASE=opsmanage
      - MYSQL_USER="opsmanage"
      - MYSQL_PASSWORD="123456"
      - MYSQL_ROOT_PASSWORD="123456"
    volumes:
      - /data/apps/mysql:/var/lib/mysql  
    restart: always  
    networks:
      - default
  ops_web:
     image: opsmanage-base:latest
     container_name: ops_web
     environment:
       MYSQL_DATABASE: opsmanage
       MYSQL_USER: "opsmanage"
       MYSQL_PASSWORD: "123456"
     ports:
       - "8000:8000" #vim /mnt/OpsManage/OpsManage/settings.py文件里面的DEBUG设置为DEBUG = True 
     volumes:
       - /data/opsmanage/OpsManage:/data/apps/opsmanage
       - /data/opsmanage/OpsManage/upload:/data/apps/opsmanage/upload
       - /data/opsmanage/OpsManage/logs:/data/apps/opsmanage/logs
     command: bash /data/apps/opsmanage/docker/start.sh  
     links:
       - db
       - redis
       - rabbitmq
     depends_on:
       - db
       - redis
       - rabbitmq
     restart: always
     networks:
       - default

另外我不确定我opsmanage.ini文件有没有配置错误，这是我的配置
[db]
engine = mysql
host = db
port = 3306
user = opsmanage
password = 123456
database = opsmanage
我试了一下在start.sh文件中输出了mysql相关的变量，都能正常的获取，所以比较奇怪，我连接mysql的容器后使用opsmanage用户和root用户登录都提示密码错误

**Comment by welliamcao** [comment]
`- MYSQL_USER="opsmanage"
- MYSQL_PASSWORD="123456"
- MYSQL_ROOT_PASSWORD="123456"`
删掉 /data/apps/mysql，去掉引号

**Comment by Sai-kk** [comment]
感谢！已经可以了
