### ISSUE TITLE
SVN发布问题

### ISSUE THREAD

**Issue by wodezz** [welliamcao/OpsManage#23]
1.如果我用的是svn来控制版本，那svn是不是要安装标准的模式下面分trunk,branch,tag来做，前面我只用一个目录来做，部署的时候一直不成功，还没找到原因。

2.还有个问题是，我觉得是不是在添加服务器的时候就确定这台服务器属于某个项目，这样在发布的时候就不用选择了，这样是不是更好。如果是在部署的时候还能修改，会不会发生漏更的问题？
谢谢回答

**Comment by welliamcao** [comment]
@wodezz 1.是的，出现错误，提供一下具体错误信息。
2.CMDB设备资产是基础，其他组件功能需要时接入就可以了，不是单一用来部署项目代码的没必要高耦合性。部署的时候默认是同时部署，但是要考虑分批部署的业务场景，所以部署的时候可以先部署一部分服务器，同时平台会提示你是否继续部署没有部署的服务器。
