### ISSUE TITLE
Docker部署时提示pull access denied for opsmanage-base

### ISSUE THREAD

**Issue by GeorgeUgly** [welliamcao/OpsManage#237]
#docker-compose up -d
Pulling ops_web (opsmanage-base:latest)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]n
ERROR: pull access denied for opsmanage-base, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by zaghost** [comment]
docker pull opsmanage-base看看报什么错

**Comment by fge2016** [comment]
你要本地先build dockerimages吧
