### ISSUE TITLE
发布的问题

### ISSUE THREAD

**Issue by wodezz** [welliamcao/OpsManage#24]
1.deploy_run.html里面关于svn库和分支版本的问题
{% if project.project_model == 'branch' and project.project_repertory == 'git' %}
{% elif project.project_model == 'tag' and  project.project_repertory == 'git' %}
{% else %}
如果我用的svn，分支是tag那就是要执行else下面的，但是下面的<input type="hidden" name="project_branch"	value="trunk" disabled/>是不POST的，我在deploy.py里面的deploy_run函数里面看到elif project.project_model == 'tag':
                    bName = request.POST.get('project_branch')这句，都没有POST数据这里怎么获取的，我不是太清楚。
还有if request.POST.get('project_mode',None) == "rollback":这句我在deploy_run.html里面没看到有name为project_mode的呢？
谢谢解答

**Comment by welliamcao** [comment]
回滚到svn或者git commit的历史点不需要指定分支或者tag。

**Comment by wodezz** [comment]
我选的测试环境，仓库类型是svn，分支上线是tag，初始化完了后，点击"部署"，在视图函数deploy_run.py应该是执行elif project.project_model == 'tag':这个分支语句下面的内容对吧？

**Comment by wodezz** [comment]
如果是测试环境 部署就会有问题

**Comment by wodezz** [comment]
utils/svn.py 里面的branch函数和tag函数返回各返回一个空列表[]是何意？

**Comment by welliamcao** [comment]
@wodezz svn没有找到获取分支或者tag的方法，所以写了空方法，代码部署尽量用git方式svn有些功能不完整。

**Comment by wodezz** [comment]
哦 就是版本控制用git 是吧 ？

**Comment by welliamcao** [comment]
对的
