### ISSUE TITLE
V3 docker下，秘钥认证始终失败

### ISSUE THREAD

**Issue by bobzhanggmail** [welliamcao/OpsManage#241]
docker方式已安装成功，启动后导入了资产，用的是“秘钥认证”方式，在ops机器上，生成秘钥后，执行了ssh-copy-id（copy的是有sudo权限的一个用户）。在机器上执行ssh命令也可以直接通过。
但是现在我在ops平台上，执行ping模块，会提示：
Failed to connect to the host via ssh: opsadm@172.31.98.71: Permission denied (publickey,password)
包括选中机器，点“更新”,也是提示失败。

如果换成密码认证方式，是可以的，秘钥认证方式始终不行。

**Comment by welliamcao** [comment]
容器默认跟宿主机是隔离的，你在宿主机copy的密钥，容器里面肯定用不了。

**Comment by bobzhanggmail** [comment]
你好，我问下，如果在容器里，我要生成id，并且ssh-copy-id拷贝到目标机上，那岂不是都只能用容器的root用户来生成？
