### ISSUE TITLE
用户权限显示空白

### ISSUE THREAD

**Issue by yangjianbo-mm** [welliamcao/OpsManage#242]
我使用的docker镜像安装的，安装了两次，用户权限过滤显示的是空白，我不知道是不是我哪里配置不对？

**Comment by yangjianbo-mm** [comment]
对应的用户权限的表已经创建上了，但是内容为空。

**Comment by welliamcao** [comment]
把这些SQL更新到数据库里面去

> 
INSERT INTO `django_content_type` VALUES ('1', 'admin', 'logentry');
INSERT INTO `django_content_type` VALUES ('69', 'apply', 'ipvs_config');
INSERT INTO `django_content_type` VALUES ('70', 'apply', 'ipvs_ns_config');
INSERT INTO `django_content_type` VALUES ('71', 'apply', 'ipvs_ops_log');
INSERT INTO `django_content_type` VALUES ('72', 'apply', 'ipvs_rs_config');
INSERT INTO `django_content_type` VALUES ('17', 'asset', 'assets');
INSERT INTO `django_content_type` VALUES ('18', 'asset', 'business_env_assets');
INSERT INTO `django_content_type` VALUES ('19', 'asset', 'business_tree_assets');
INSERT INTO `django_content_type` VALUES ('20', 'asset', 'cabinet_assets');
INSERT INTO `django_content_type` VALUES ('21', 'asset', 'disk_assets');
INSERT INTO `django_content_type` VALUES ('22', 'asset', 'idc_assets');
INSERT INTO `django_content_type` VALUES ('23', 'asset', 'idle_assets');
INSERT INTO `django_content_type` VALUES ('24', 'asset', 'line_assets');
INSERT INTO `django_content_type` VALUES ('26', 'asset', 'networkcard_assets');
INSERT INTO `django_content_type` VALUES ('25', 'asset', 'network_assets');
INSERT INTO `django_content_type` VALUES ('27', 'asset', 'raid_assets');
INSERT INTO `django_content_type` VALUES ('28', 'asset', 'ram_assets');
INSERT INTO `django_content_type` VALUES ('29', 'asset', 'server_assets');
INSERT INTO `django_content_type` VALUES ('30', 'asset', 'tags_assets');
INSERT INTO `django_content_type` VALUES ('31', 'asset', 'tags_server_assets');
INSERT INTO `django_content_type` VALUES ('32', 'asset', 'user_server');
INSERT INTO `django_content_type` VALUES ('33', 'asset', 'zone_assets');
INSERT INTO `django_content_type` VALUES ('3', 'auth', 'group');
INSERT INTO `django_content_type` VALUES ('2', 'auth', 'permission');
INSERT INTO `django_content_type` VALUES ('54', 'cicd', 'log_project_config');
INSERT INTO `django_content_type` VALUES ('55', 'cicd', 'log_project_record');
INSERT INTO `django_content_type` VALUES ('56', 'cicd', 'project_config');
INSERT INTO `django_content_type` VALUES ('57', 'cicd', 'project_roles');
INSERT INTO `django_content_type` VALUES ('4', 'contenttypes', 'contenttype');
INSERT INTO `django_content_type` VALUES ('10', 'databases', 'custom_high_risk_sql');
INSERT INTO `django_content_type` VALUES ('11', 'databases', 'database_detail');
INSERT INTO `django_content_type` VALUES ('12', 'databases', 'database_group');
INSERT INTO `django_content_type` VALUES ('13', 'databases', 'database_server_config');
INSERT INTO `django_content_type` VALUES ('14', 'databases', 'database_table_detail_record');
INSERT INTO `django_content_type` VALUES ('15', 'databases', 'database_user');
INSERT INTO `django_content_type` VALUES ('16', 'databases', 'sql_execute_histroy');
INSERT INTO `django_content_type` VALUES ('34', 'deploy', 'deploy_callback_model_result');
INSERT INTO `django_content_type` VALUES ('35', 'deploy', 'deploy_callback_playbook_result');
INSERT INTO `django_content_type` VALUES ('36', 'deploy', 'deploy_inventory');
INSERT INTO `django_content_type` VALUES ('37', 'deploy', 'deploy_inventory_groups');
INSERT INTO `django_content_type` VALUES ('38', 'deploy', 'deploy_inventory_groups_server');
INSERT INTO `django_content_type` VALUES ('39', 'deploy', 'deploy_playbook');
INSERT INTO `django_content_type` VALUES ('40', 'deploy', 'deploy_script');
INSERT INTO `django_content_type` VALUES ('41', 'deploy', 'log_deploy_model');
INSERT INTO `django_content_type` VALUES ('42', 'deploy', 'log_deploy_playbook');
INSERT INTO `django_content_type` VALUES ('63', 'django_celery_beat', 'crontabschedule');
INSERT INTO `django_content_type` VALUES ('64', 'django_celery_beat', 'intervalschedule');
INSERT INTO `django_content_type` VALUES ('65', 'django_celery_beat', 'periodictask');
INSERT INTO `django_content_type` VALUES ('66', 'django_celery_beat', 'periodictasks');
INSERT INTO `django_content_type` VALUES ('67', 'django_celery_beat', 'solarschedule');
INSERT INTO `django_content_type` VALUES ('68', 'django_celery_results', 'taskresult');
INSERT INTO `django_content_type` VALUES ('51', 'filemanage', 'filedownload_audit_order');
INSERT INTO `django_content_type` VALUES ('52', 'filemanage', 'fileupload_audit_order');
INSERT INTO `django_content_type` VALUES ('53', 'filemanage', 'uploadfiles');
INSERT INTO `django_content_type` VALUES ('6', 'navbar', 'nav_third');
INSERT INTO `django_content_type` VALUES ('7', 'navbar', 'nav_third_number');
INSERT INTO `django_content_type` VALUES ('8', 'navbar', 'nav_type');
INSERT INTO `django_content_type` VALUES ('9', 'navbar', 'nav_type_number');
INSERT INTO `django_content_type` VALUES ('43', 'orders', 'order_notice_config');
INSERT INTO `django_content_type` VALUES ('44', 'orders', 'order_system');
INSERT INTO `django_content_type` VALUES ('45', 'orders', 'sql_audit_order');
INSERT INTO `django_content_type` VALUES ('46', 'orders', 'sql_order_execute_result');
INSERT INTO `django_content_type` VALUES ('58', 'sched', 'cron_config');
INSERT INTO `django_content_type` VALUES ('59', 'sched', 'log_cron_config');
INSERT INTO `django_content_type` VALUES ('60', 'sched', 'sched_job_config');
INSERT INTO `django_content_type` VALUES ('61', 'sched', 'sched_job_logs');
INSERT INTO `django_content_type` VALUES ('62', 'sched', 'sched_node');
INSERT INTO `django_content_type` VALUES ('5', 'sessions', 'session');
INSERT INTO `django_content_type` VALUES ('47', 'wiki', 'category');
INSERT INTO `django_content_type` VALUES ('48', 'wiki', 'comment');
INSERT INTO `django_content_type` VALUES ('49', 'wiki', 'post');
INSERT INTO `django_content_type` VALUES ('50', 'wiki', 'tag');
INSERT INTO `auth_permission` VALUES ('1', 'Can add log entry', '1', 'add_logentry');
INSERT INTO `auth_permission` VALUES ('2', 'Can change log entry', '1', 'change_logentry');
INSERT INTO `auth_permission` VALUES ('3', 'Can delete log entry', '1', 'delete_logentry');
INSERT INTO `auth_permission` VALUES ('4', 'Can view log entry', '1', 'view_logentry');
INSERT INTO `auth_permission` VALUES ('5', 'Can add permission', '2', 'add_permission');
INSERT INTO `auth_permission` VALUES ('6', 'Can change permission', '2', 'change_permission');
INSERT INTO `auth_permission` VALUES ('7', 'Can delete permission', '2', 'delete_permission');
INSERT INTO `auth_permission` VALUES ('8', 'Can view permission', '2', 'view_permission');
INSERT INTO `auth_permission` VALUES ('9', 'Can add group', '3', 'add_group');
INSERT INTO `auth_permission` VALUES ('10', 'Can change group', '3', 'change_group');
INSERT INTO `auth_permission` VALUES ('11', 'Can delete group', '3', 'delete_group');
INSERT INTO `auth_permission` VALUES ('12', 'Can view group', '3', 'view_group');
INSERT INTO `auth_permission` VALUES ('13', 'Can add content type', '4', 'add_contenttype');
INSERT INTO `auth_permission` VALUES ('14', 'Can change content type', '4', 'change_contenttype');
INSERT INTO `auth_permission` VALUES ('15', 'Can delete content type', '4', 'delete_contenttype');
INSERT INTO `auth_permission` VALUES ('16', 'Can view content type', '4', 'view_contenttype');
INSERT INTO `auth_permission` VALUES ('17', 'Can add session', '5', 'add_session');
INSERT INTO `auth_permission` VALUES ('18', 'Can change session', '5', 'change_session');
INSERT INTO `auth_permission` VALUES ('19', 'Can delete session', '5', 'delete_session');
INSERT INTO `auth_permission` VALUES ('20', 'Can view session', '5', 'view_session');
INSERT INTO `auth_permission` VALUES ('21', '读取站内导航权限', '8', 'nav_read_nav_type');
INSERT INTO `auth_permission` VALUES ('22', '更改站内导航权限', '8', 'nav_change_nav_type');
INSERT INTO `auth_permission` VALUES ('23', '添加站内导航权限', '8', 'nav_add_nav_type');
INSERT INTO `auth_permission` VALUES ('24', '删除站内导航权限', '8', 'nav_delete_nav_type');
INSERT INTO `auth_permission` VALUES ('25', '读取站内导航详情权限', '9', 'nav_read_nav_number');
INSERT INTO `auth_permission` VALUES ('26', '更改站内导航详情权限', '9', 'nav_change_nav_number');
INSERT INTO `auth_permission` VALUES ('27', '添加站内导航详情权限', '9', 'nav_add_nav_number');
INSERT INTO `auth_permission` VALUES ('28', '删除站内导航详情权限', '9', 'nav_delete_nav_number');
INSERT INTO `auth_permission` VALUES ('29', '读取高危SQL表权限', '10', 'database_read_custom_high_risk_sql');
INSERT INTO `auth_permission` VALUES ('30', '更改高危SQL表权限', '10', 'database_change_custom_high_risk_sql');
INSERT INTO `auth_permission` VALUES ('31', '添加高危SQL表权限', '10', 'database_add_custom_high_risk_sql');
INSERT INTO `auth_permission` VALUES ('32', '删除高危SQL表权限', '10', 'database_delete_custom_high_risk_sql');
INSERT INTO `auth_permission` VALUES ('33', '读取数据库信息表权限', '13', 'database_read_database_server_config');
INSERT INTO `auth_permission` VALUES ('34', '更改数据库信息表权限', '13', 'database_change_database_server_config');
INSERT INTO `auth_permission` VALUES ('35', '添加数据库信息表权限', '13', 'database_add_database_server_config');
INSERT INTO `auth_permission` VALUES ('36', '删除数据库信息表权限', '13', 'database_delete_database_server_config');
INSERT INTO `auth_permission` VALUES ('37', '数据库查询查询权限', '13', 'database_query_database_server_config');
INSERT INTO `auth_permission` VALUES ('38', '数据库执行DML语句权限', '13', 'databases_dml_database_server_config');
INSERT INTO `auth_permission` VALUES ('39', '数据库Binglog解析权限', '13', 'database_binlog_database_server_config');
INSERT INTO `auth_permission` VALUES ('40', '数据库表结构查询权限', '13', 'database_schema_database_server_config');
INSERT INTO `auth_permission` VALUES ('41', '数据库SQL优化建议权限', '13', 'database_optimize_database_server_config');
INSERT INTO `auth_permission` VALUES ('42', '读取SQL执行历史表权限', '16', 'database_read_sql_execute_histroy');
INSERT INTO `auth_permission` VALUES ('43', '更改SQL执行历史表权限', '16', 'database_change_sql_execute_histroy');
INSERT INTO `auth_permission` VALUES ('44', '添加SQL执行历史表权限', '16', 'database_add_sql_execute_histroy');
INSERT INTO `auth_permission` VALUES ('45', '删除SQL执行历史表权限', '16', 'database_delete_sql_execute_histroy');
INSERT INTO `auth_permission` VALUES ('46', '读取资产权限', '17', 'assets_read_assets');
INSERT INTO `auth_permission` VALUES ('47', '更改资产权限', '17', 'assets_change_assets');
INSERT INTO `auth_permission` VALUES ('48', '添加资产权限', '17', 'assets_add_assets');
INSERT INTO `auth_permission` VALUES ('49', '删除资产权限', '17', 'assets_delete_assets');
INSERT INTO `auth_permission` VALUES ('50', '导出资产权限', '17', 'assets_dumps_assets');
INSERT INTO `auth_permission` VALUES ('51', '读取业务资产权限', '19', 'assets_read_business');
INSERT INTO `auth_permission` VALUES ('52', '编辑业务资产权限', '19', 'assets_change_business');
INSERT INTO `auth_permission` VALUES ('53', '添加业务资产权限', '19', 'assets_add_business');
INSERT INTO `auth_permission` VALUES ('54', '删除业务资产权限', '19', 'assets_delete_business');
INSERT INTO `auth_permission` VALUES ('55', '读取磁盘资产权限', '21', 'assets_read_disk');
INSERT INTO `auth_permission` VALUES ('56', '更改磁盘资产权限', '21', 'assets_change_disk');
INSERT INTO `auth_permission` VALUES ('57', '添加磁盘资产权限', '21', 'assets_add_disk');
INSERT INTO `auth_permission` VALUES ('58', '删除磁盘资产权限', '21', 'assets_delete_disk');
INSERT INTO `auth_permission` VALUES ('59', '读取出口线路资产权限', '24', 'assets_read_line');
INSERT INTO `auth_permission` VALUES ('60', '更改出口线路资产权限', '24', 'assets_change_line');
INSERT INTO `auth_permission` VALUES ('61', '添加出口线路资产权限', '24', 'assets_add_line');
INSERT INTO `auth_permission` VALUES ('62', '删除出口线路资产权限', '24', 'assets_delete_line');
INSERT INTO `auth_permission` VALUES ('63', '读取网络资产权限', '25', 'assets_read_network');
INSERT INTO `auth_permission` VALUES ('64', '更改网络资产权限', '25', 'assets_change_network');
INSERT INTO `auth_permission` VALUES ('65', '添加网络资产权限', '25', 'assets_add_network');
INSERT INTO `auth_permission` VALUES ('66', '删除网络资产权限', '25', 'assets_delete_network');
INSERT INTO `auth_permission` VALUES ('67', '读取Raid资产权限', '27', 'assets_read_raid');
INSERT INTO `auth_permission` VALUES ('68', '更改Raid资产权限', '27', 'assets_change_raid');
INSERT INTO `auth_permission` VALUES ('69', '添加Raid资产权限', '27', 'assets_add_raid');
INSERT INTO `auth_permission` VALUES ('70', '删除Raid资产权限', '27', 'assets_delete_raid');
INSERT INTO `auth_permission` VALUES ('71', '读取内存资产权限', '28', 'assets_read_ram');
INSERT INTO `auth_permission` VALUES ('72', '更改内存资产权限', '28', 'assets_change_ram');
INSERT INTO `auth_permission` VALUES ('73', '添加内存资产权限', '28', 'assets_add_ram');
INSERT INTO `auth_permission` VALUES ('74', '删除内存资产权限', '28', 'assets_delete_ram');
INSERT INTO `auth_permission` VALUES ('75', '读取服务器资产权限', '29', 'assets_read_server');
INSERT INTO `auth_permission` VALUES ('76', '更改服务器资产权限', '29', 'assets_change_server');
INSERT INTO `auth_permission` VALUES ('77', '添加服务器资产权限', '29', 'assets_add_server');
INSERT INTO `auth_permission` VALUES ('78', '删除服务器资产权限', '29', 'assets_delete_server');
INSERT INTO `auth_permission` VALUES ('79', '登陆服务器资产权限', '29', 'assets_webssh_server');
INSERT INTO `auth_permission` VALUES ('80', '读取标签资产权限', '30', 'assets_read_tags');
INSERT INTO `auth_permission` VALUES ('81', '更改标签资产权限', '30', 'assets_change_tags');
INSERT INTO `auth_permission` VALUES ('82', '添加标签资产权限', '30', 'assets_add_tags');
INSERT INTO `auth_permission` VALUES ('83', '删除标签资产权限', '30', 'assets_delete_tags');
INSERT INTO `auth_permission` VALUES ('84', '读取资产树权限', '30', 'assets_read_tree');
INSERT INTO `auth_permission` VALUES ('85', '添加用户权限', '32', 'assets_add_user');
INSERT INTO `auth_permission` VALUES ('86', '修改用户权限', '32', 'assets_change_user');
INSERT INTO `auth_permission` VALUES ('87', '删除用户权限', '32', 'assets_delete_user');
INSERT INTO `auth_permission` VALUES ('88', '读取用户权限', '32', 'assets_read_user');
INSERT INTO `auth_permission` VALUES ('89', '读取区域机房权限', '33', 'assets_read_zone');
INSERT INTO `auth_permission` VALUES ('90', '更改区域机房权限', '33', 'assets_change_zone');
INSERT INTO `auth_permission` VALUES ('91', '添加区域机房权限', '33', 'assets_add_zone');
INSERT INTO `auth_permission` VALUES ('92', '删除区域机房权限', '33', 'assets_delete_zone');
INSERT INTO `auth_permission` VALUES ('93', '读取部署资产权限', '36', 'deploy_read_deploy_inventory');
INSERT INTO `auth_permission` VALUES ('94', '修改部署资产权限', '36', 'deploy_change_deploy_inventory');
INSERT INTO `auth_permission` VALUES ('95', '添加部署资产权限', '36', 'deploy_add_deploy_inventory');
INSERT INTO `auth_permission` VALUES ('96', '删除部署资产权限', '36', 'deploy_delete_deploy_inventory');
INSERT INTO `auth_permission` VALUES ('97', '读取部署剧本权限', '39', 'deploy_read_deploy_playbook');
INSERT INTO `auth_permission` VALUES ('98', '修改部署剧本权限', '39', 'deploy_change_deploy_playbook');
INSERT INTO `auth_permission` VALUES ('99', '添加部署剧本权限', '39', 'deploy_add_deploy_playbook');
INSERT INTO `auth_permission` VALUES ('100', '删除部署剧本权限', '39', 'deploy_delete_deploy_playbook');
INSERT INTO `auth_permission` VALUES ('101', '执行部署剧本权限', '39', 'deploy_exec_deploy_playbook');
INSERT INTO `auth_permission` VALUES ('102', '读取部署脚本权限', '40', 'deploy_read_deploy_script');
INSERT INTO `auth_permission` VALUES ('103', '修改部署脚本权限', '40', 'deploy_change_deploy_script');
INSERT INTO `auth_permission` VALUES ('104', '添加部署脚本权限', '40', 'deploy_add_deploy_script');
INSERT INTO `auth_permission` VALUES ('105', '删除部署脚本权限', '40', 'deploy_delete_deploy_script');
INSERT INTO `auth_permission` VALUES ('106', '执行部署脚本权限', '40', 'deploy_exec_deploy_script');
INSERT INTO `auth_permission` VALUES ('107', '执行部署模块权限', '40', 'deploy_exec_deploy_model');
INSERT INTO `auth_permission` VALUES ('108', '读取部署模块权限', '40', 'deploy_read_deploy_model');
INSERT INTO `auth_permission` VALUES ('109', '读取部署模块执行记录权限', '41', 'deploy_read_log_deploy_model');
INSERT INTO `auth_permission` VALUES ('110', '修改部署模块执行记录权限', '41', 'deploy_change_log_deploy_model');
INSERT INTO `auth_permission` VALUES ('111', '添加部署模块执行记录权限', '41', 'deploy_add_log_deploy_model');
INSERT INTO `auth_permission` VALUES ('112', '删除部署模块执行记录权限', '41', 'deploy_delete_log_deploy_model');
INSERT INTO `auth_permission` VALUES ('113', '读取部署剧本执行记录权限', '42', 'deploy_read_log_deploy_playbook');
INSERT INTO `auth_permission` VALUES ('114', '修改部署剧本执行记录权限', '42', 'deploy_change_log_deploy_playbook');
INSERT INTO `auth_permission` VALUES ('115', '添加部署剧本执行记录权限', '42', 'deploy_add_log_deploy_playbook');
INSERT INTO `auth_permission` VALUES ('116', '删除部署剧本执行记录权限', '42', 'deploy_delete_log_deploy_playbook');
INSERT INTO `auth_permission` VALUES ('117', '读取工单通知配置表权限', '43', 'orders_read_notice_config');
INSERT INTO `auth_permission` VALUES ('118', '更改工单通知配置表权限', '43', 'orders_change_notice_config');
INSERT INTO `auth_permission` VALUES ('119', '添加工单通知配置表权限', '43', 'orders_add_notice_config');
INSERT INTO `auth_permission` VALUES ('120', '删除工单通知配置表权限', '43', 'orders_delete_notice_config');
INSERT INTO `auth_permission` VALUES ('121', '读取工单系统权限', '44', 'orders_read_order_system');
INSERT INTO `auth_permission` VALUES ('122', '更改工单系统权限', '44', 'orders_change_order_systemr');
INSERT INTO `auth_permission` VALUES ('123', '添加工单系统权限', '44', 'orders_add_order_system');
INSERT INTO `auth_permission` VALUES ('124', '删除工单系统权限', '44', 'orders_delete_order_system');
INSERT INTO `auth_permission` VALUES ('125', '读取SQL审核工单权限', '45', 'orders_read_sql_audit_order');
INSERT INTO `auth_permission` VALUES ('126', '更改SQL审核工单权限', '45', 'orders_change_sql_audit_order');
INSERT INTO `auth_permission` VALUES ('127', '添加SQL审核工单权限', '45', 'orders_add_sql_audit_order');
INSERT INTO `auth_permission` VALUES ('128', '删除SQL审核工单权限', '45', 'orders_delete_sql_audit_order');
INSERT INTO `auth_permission` VALUES ('129', '读取分类权限', '47', 'wiki_can_read_wiki_category');
INSERT INTO `auth_permission` VALUES ('130', '更改分类权限', '47', 'wiki_can_change_wiki_category');
INSERT INTO `auth_permission` VALUES ('131', '添加分类权限', '47', 'wiki_can_add_wiki_category');
INSERT INTO `auth_permission` VALUES ('132', '删除分类权限', '47', 'wiki_can_delete_wiki_category');
INSERT INTO `auth_permission` VALUES ('133', '读取评论权限', '48', 'wiki_can_read_wiki_comment');
INSERT INTO `auth_permission` VALUES ('134', '更改评论权限', '48', 'wiki_can_change_wiki_comment');
INSERT INTO `auth_permission` VALUES ('135', '添加评论权限', '48', 'wiki_can_add_wiki_comment');
INSERT INTO `auth_permission` VALUES ('136', '删除评论权限', '48', 'wiki_can_delete_wiki_comment');
INSERT INTO `auth_permission` VALUES ('137', '读取文章权限', '49', 'wiki_can_read_wiki_post');
INSERT INTO `auth_permission` VALUES ('138', '更改文章权限', '49', 'wiki_can_change_wiki_post');
INSERT INTO `auth_permission` VALUES ('139', '添加文章权限', '49', 'wiki_can_add_wiki_post');
INSERT INTO `auth_permission` VALUES ('140', '删除文章权限', '49', 'wiki_can_delete_wiki_post');
INSERT INTO `auth_permission` VALUES ('141', '读取标签权限', '50', 'wiki_can_read_wiki_tag');
INSERT INTO `auth_permission` VALUES ('142', '更改标签权限', '50', 'wiki_can_change_wiki_tag');
INSERT INTO `auth_permission` VALUES ('143', '添加标签权限', '50', 'wiki_can_add_wiki_tag');
INSERT INTO `auth_permission` VALUES ('144', '删除标签权限', '50', 'wiki_can_delete_wiki_tag');
INSERT INTO `auth_permission` VALUES ('145', '读取文件下载审核工单权限', '51', 'filemanage_read_filedownload_audit_order');
INSERT INTO `auth_permission` VALUES ('146', '更改文件下载审核工单权限', '51', 'filemanage_change_filedownload_audit_order');
INSERT INTO `auth_permission` VALUES ('147', '添加文件下载审核工单权限', '51', 'filemanage_add_filedownload_audit_order');
INSERT INTO `auth_permission` VALUES ('148', '删除文件下载审核工单权限', '51', 'filemanage_delete_filedownload_audit_order');
INSERT INTO `auth_permission` VALUES ('149', '读取文件上传审核工单权限', '52', 'filemanage_read_fileupload_audit_order');
INSERT INTO `auth_permission` VALUES ('150', '更改文件上传审核工单权限', '52', 'filemanage_change_fileupload_audit_order');
INSERT INTO `auth_permission` VALUES ('151', '添加文件上传审核工单权限', '52', 'filemanage_add_fileupload_audit_order');
INSERT INTO `auth_permission` VALUES ('152', '删除文件上传审核工单权限', '52', 'filemanage_delete_fileupload_audit_order');
INSERT INTO `auth_permission` VALUES ('153', '读取项目部署权限', '56', 'project_read_project_config');
INSERT INTO `auth_permission` VALUES ('154', '更改项目部署权限', '56', 'project_change_project_config');
INSERT INTO `auth_permission` VALUES ('155', '添加项目部署权限', '56', 'project_add_project_config');
INSERT INTO `auth_permission` VALUES ('156', '删除项目部署权限', '56', 'project_delete_project_config');
INSERT INTO `auth_permission` VALUES ('157', '读取任务配置权限', '58', 'sched_can_read_cron_config');
INSERT INTO `auth_permission` VALUES ('158', '更改任务配置权限', '58', 'sched_can_change_cron_config');
INSERT INTO `auth_permission` VALUES ('159', '添加任务配置权限', '58', 'sched_can_add_cron_config');
INSERT INTO `auth_permission` VALUES ('160', '删除任务配置权限', '58', 'sched_can_delete_cron_config');
INSERT INTO `auth_permission` VALUES ('161', 'Can add crontab', '63', 'add_crontabschedule');
INSERT INTO `auth_permission` VALUES ('162', 'Can change crontab', '63', 'change_crontabschedule');
INSERT INTO `auth_permission` VALUES ('163', 'Can delete crontab', '63', 'delete_crontabschedule');
INSERT INTO `auth_permission` VALUES ('164', 'Can view crontab', '63', 'view_crontabschedule');
INSERT INTO `auth_permission` VALUES ('165', 'Can add interval', '64', 'add_intervalschedule');
INSERT INTO `auth_permission` VALUES ('166', 'Can change interval', '64', 'change_intervalschedule');
INSERT INTO `auth_permission` VALUES ('167', 'Can delete interval', '64', 'delete_intervalschedule');
INSERT INTO `auth_permission` VALUES ('168', 'Can view interval', '64', 'view_intervalschedule');
INSERT INTO `auth_permission` VALUES ('169', 'Can add periodic task', '65', 'add_periodictask');
INSERT INTO `auth_permission` VALUES ('170', 'Can change periodic task', '65', 'change_periodictask');
INSERT INTO `auth_permission` VALUES ('171', 'Can delete periodic task', '65', 'delete_periodictask');
INSERT INTO `auth_permission` VALUES ('172', 'Can view periodic task', '65', 'view_periodictask');
INSERT INTO `auth_permission` VALUES ('173', 'Can add periodic tasks', '66', 'add_periodictasks');
INSERT INTO `auth_permission` VALUES ('174', 'Can change periodic tasks', '66', 'change_periodictasks');
INSERT INTO `auth_permission` VALUES ('175', 'Can delete periodic tasks', '66', 'delete_periodictasks');
INSERT INTO `auth_permission` VALUES ('176', 'Can view periodic tasks', '66', 'view_periodictasks');
INSERT INTO `auth_permission` VALUES ('177', 'Can add solar event', '67', 'add_solarschedule');
INSERT INTO `auth_permission` VALUES ('178', 'Can change solar event', '67', 'change_solarschedule');
INSERT INTO `auth_permission` VALUES ('179', 'Can delete solar event', '67', 'delete_solarschedule');
INSERT INTO `auth_permission` VALUES ('180', 'Can view solar event', '67', 'view_solarschedule');
INSERT INTO `auth_permission` VALUES ('181', 'Can add task result', '68', 'add_taskresult');
INSERT INTO `auth_permission` VALUES ('182', 'Can change task result', '68', 'change_taskresult');
INSERT INTO `auth_permission` VALUES ('183', 'Can delete task result', '68', 'delete_taskresult');
INSERT INTO `auth_permission` VALUES ('184', 'Can view task result', '68', 'view_taskresult');
INSERT INTO `auth_permission` VALUES ('185', '读取IPVS信息表权限', '69', 'ipvs_read_ipvs_config');
INSERT INTO `auth_permission` VALUES ('186', '更改IPVS信息表权限', '69', 'ipvs_change_ipvs_config');
INSERT INTO `auth_permission` VALUES ('187', '添加IPVS信息表权限', '69', 'ipvs_add_ipvs_config');
INSERT INTO `auth_permission` VALUES ('188', '删除IPVS信息表权限', '69', 'ipvs_delete_ipvs_config');
INSERT INTO `auth_permission` VALUES ('189', '读取用户权限', '73', 'users_read_user');
INSERT INTO `auth_permission` VALUES ('190', '修改用户权限', '73', 'users_change_user');
INSERT INTO `auth_permission` VALUES ('191', '添加用户权限', '73', 'users_add_user');
INSERT INTO `auth_permission` VALUES ('192', '删除用户权限', '73', 'users_delete_user');
INSERT INTO `auth_permission` VALUES ('193', '读取用户组权限', '74', 'user_read_groups');
INSERT INTO `auth_permission` VALUES ('194', '修改用户组权限', '74', 'user_change_groups');
INSERT INTO `auth_permission` VALUES ('195', '添加用户组权限', '74', 'user_add_groups');
INSERT INTO `auth_permission` VALUES ('196', '删除用户组权限', '74', 'user_delete_groups');
INSERT INTO `auth_permission` VALUES ('197', '读取用户角色权限', '75', 'users_read_role');
INSERT INTO `auth_permission` VALUES ('198', '修改用户角色权限', '75', 'users_change_role');
INSERT INTO `auth_permission` VALUES ('199', '添加用户角色权限', '75', 'users_add_role');
INSERT INTO `auth_permission` VALUES ('200', '删除用户角色权限', '75', 'users_delete_role');
`

**Comment by yangjianbo-mm** [comment]
问题解决了。感谢。
