### ISSUE TITLE
为何无supervisord及supervisorctl命令？

### ISSUE THREAD

**Issue by zenglingmin168** [welliamcao/OpsManage#248]
1. # echo_supervisord_conf > /etc/supervisord.conf   这步报错，没有命令

2. 启动celery
# supervisord -c /etc/supervisord.conf
# supervisorctl status #要检查是否都是running状态，uptime是不是递增
这些命令也都没有

前面的步骤都是成功的，请大佬指教，在线等

**Comment by welliamcao** [comment]
这个命令有可能在/usr/local/bin或者/usr/bin，你找找看。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zenglingmin168 <notifications@github.com&gt;
发送时间: 2020年2月20日 17:24
收件人: welliamcao/OpsManage <OpsManage@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[welliamcao/OpsManage] 为何无supervisord及supervisorctl命令？ (#248)



 
 
echo_supervisord_conf &gt; /etc/supervisord.conf   这步报错，没有命令
 

 
启动celery
 
 
supervisord -c /etc/supervisord.conf
 
supervisorctl status #要检查是否都是running状态，uptime是不是递增
 
这些命令也都没有
 
前面的步骤都是成功的，请大佬指教，在线等

**Comment by zenglingmin168** [comment]
真没有，我找了。而且，如果有的话，我直接执行命令，应该不会报命令不存在的。您这个步骤是完整 的吧，应该没有遗漏吧？

**Comment by zenglingmin168** [comment]
问题解决了，是supervisor没装，你文档里边没有，还是我自己知识储备不够。谢谢大佬了

**Comment by zenglingmin168** [comment]
又碰到了另外一个问题，平台搭建好之后，登陆账号、密码是多少，在哪配置的？setting.py这个文件需要配置吗？还望大佬指教，在线等

**Comment by welliamcao** [comment]
/usr/local/python3/bin/python3 manage.py createsuperuser  #创建管理员账户与密码
这一步你配置的就是管理员账户与密码

**Comment by zenglingmin168** [comment]
明白。登入了，非常感谢！------------------ 原始邮件 ------------------
发件人: "William.Cao"<notifications@github.com>
发送时间: 2020年2月20日(星期四) 晚上10:15
收件人: "welliamcao/OpsManage"<OpsManage@noreply.github.com>;
抄送: "zenglingmin168"<3108775440@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [welliamcao/OpsManage] 为何无supervisord及supervisorctl命令？ (#248)



/usr/local/python3/bin/python3 manage.py createsuperuser  #创建管理员账户与密码
 这一步你配置的就是管理员账户与密码
 
&mdash;
