### ISSUE TITLE
添加资产时,raid类型无法选择

### ISSUE THREAD

**Issue by R1hug0** [welliamcao/OpsManage#25]
没有弹出可用类型

**Comment by welliamcao** [comment]
先配置基础资产里面的raid项

**Comment by R1hug0** [comment]
YES,找到了,顺便问下为啥在基础资产添加相关组时会弹出添加资产失败的框 ,但马上又消失,就是一闪.

**Comment by welliamcao** [comment]
会自动刷新页面，你可以捕捉一下返回的respone内容，定位一下故障。

**Comment by R1hug0** [comment]
没啥明显的错误,弹失败时有这样的失败请求
 "POST /api/server/ HTTP/1.1" 400 103		  
 "PUT /api/group/3/ HTTP/1.1" 500 14856
