### ISSUE TITLE
新版本V3服务器资产信息中没有所属产品线和业务类型

### ISSUE THREAD

**Issue by baishuyou** [welliamcao/OpsManage#250]
新版本V3服务器资产信息中没有所属产品线和业务类型，这方面的信息在什么位置可以修改呢
建立业务线的时候也无法选择主机，应该是服务器和产品线未对应导致的，不知道从何处设置对应关系

**Comment by baishuyou** [comment]
找到了，在业务树下，要选择一个环境点击进去进行关联主机

**Comment by Zhang21** [comment]
我也是找了半天，看到你的说明才找到了。谢谢。
