### ISSUE TITLE
数据库查询无法出数据，http 连接一直处于pending状态

### ISSUE THREAD

**Issue by baishuyou** [welliamcao/OpsManage#251]
![111](https://user-images.githubusercontent.com/26220328/75106555-e9551700-5658-11ea-9f43-19d416294d87.png)

**Comment by welliamcao** [comment]
有可能要返回的数据量太多了，加limit看看

**Comment by baishuyou** [comment]
![image](https://user-images.githubusercontent.com/26220328/75124102-fc62f800-56e7-11ea-8463-49e3baa867ad.png)
加了limit也是一样，没返回数据

**Comment by welliamcao** [comment]
supervisorctl status 看看是不是celery没有启动

**Comment by welliamcao** [comment]
参考https://github.com/welliamcao/OpsManage/issues/254#issuecomment-599851264

**Comment by ltgentoo** [comment]
兄弟我跟你一样的问题，把
OpsManage/__init__.py中
from celery import app as celery_app
改为
from .celery import app as celery_app
可以解决
