### ISSUE TITLE
大佬好！请教几个问题：如何批量导入设备资产信息？如何通过api获取各平台（如阿里云）资产信息？敬请指教。

### ISSUE THREAD

**Issue by zenglingmin168** [welliamcao/OpsManage#253]

**Comment by welliamcao** [comment]
1、用户中心资产管理有导入按钮
2、api要自己开发

**Comment by zenglingmin168** [comment]
噢，好的，我再找找，谢谢大佬

**Comment by strugglehonor** [comment]
大佬你好，我是学生党，最近在学写CMDB，想请教下采集到资产数据后，发送给API的时候，这个发送过程你是怎么做的呢，是加密还是怎样，可以指教一下小弟吗

**Comment by welliamcao** [comment]
没有加密，采用的是用ansible api pull的方式，不是通过agent push收集。

**Comment by strugglehonor** [comment]
OK，谢谢哈，请问可以让我进下QQ群吗，刚刚加了，昵称是struggle
