### ISSUE TITLE
请问关于用户权限是在什么地方设置？

### ISSUE THREAD

**Issue by guolvting4u** [welliamcao/OpsManage#255]
我在页面的用户管理下，只有用户中心和用户管理2个子菜单。用户管理中，只能指定用户是普通用户，还是超级用户，以及给用户指定资产。并没有找到和权限相关的设置

**Comment by welliamcao** [comment]
![image](https://user-images.githubusercontent.com/5885314/76761649-c686d000-67ca-11ea-989f-0c2e61cd6650.png)

**Comment by guolvting4u** [comment]
截图打不开

**Comment by guolvting4u** [comment]
截图已经看见了，谢谢！
