### ISSUE TITLE
执行/usr/local/python3/bin/python3 manage.py makemigrations account

### ISSUE THREAD

**Issue by wangnannan** [welliamcao/OpsManage#257]
出现以下错误App 'account' could not be found. Is it in INSTALLED_APPS?
版本3.0.1

**Comment by welliamcao** [comment]
你是用了3.0.1版本的release包吗？那你要看包里面的readme文档，不要看github的

**Comment by wangnannan** [comment]
对，后来我就看了包里的，已经成功安装了，就是不知道咋使用，没有说明文档吗

**Comment by wangnannan** [comment]
@welliamcao 有没有使用说明文档啊

**Comment by welliamcao** [comment]
没有哦，只能自己摸索

**Comment by wangnannan** [comment]
我太难 了
