### ISSUE TITLE
WebSSH即将推出

### ISSUE THREAD

**Issue by welliamcao** [welliamcao/OpsManage#27]
![20170910205800](https://user-images.githubusercontent.com/5885314/30249280-7d47ef4c-966b-11e7-898e-44513fd7945b.png)
![20170910210253](https://user-images.githubusercontent.com/5885314/30249281-7d8ae144-966b-11e7-9b18-db0fce1d0621.png)

**Comment by mission802** [comment]
👍

**Comment by vTNT** [comment]
哥， 你项目增加几个tag吧， 让更多人搜到，

**Comment by welliamcao** [comment]
@vTNT 不知道要加什么，比如呢？

**Comment by welliamcao** [comment]
webssh功能已经上传到beta分支，因为是利用gateone实现的功能，所以需要先安装好gateone，并且配置成api认证模式，然后再配置OpsManage的setting.py文件。
![webssh](https://user-images.githubusercontent.com/5885314/30510153-4dab7e4a-9af1-11e7-913f-b9778b4babee.png)

**Comment by welliamcao** [comment]
master分支已用django+channels原生方式实现，issues关闭
