### ISSUE TITLE
[需求建议]支持云堡垒机功能

### ISSUE THREAD

**Issue by nondevops** [welliamcao/OpsManage#271]
[需求建议]支持云堡垒机功能
需求背景: 当前商业堡垒机费用不仅昂贵,许多公司望而却步,而且还非常不好用,但堡垒机功能在运维工作中及公司IT审计中起着非常核心的用途,是运维必不可少的工具,同时也是运维在日常工作中录像回放,故障追踪的好助手,希望排期支持;
需求说明: 可与开源的JUMPSERVER堡垒机阉割集成

**Comment by welliamcao** [comment]
好的，不过前期功能开发更多是以自动化为主%>_<%
