### ISSUE TITLE
/apps/api/url.py 上面引用的views没有开源吗

### ISSUE THREAD

**Issue by suyh1988** [welliamcao/OpsManage#273]
/apps/api/url.py 上面引用的views没有开源吗
from api.views import (assets_api,deploy_api,mysql_api,
                       orders_api,cron_api,celery_api,
                       cicd_api,monitor_api,nav_api,
                       wiki_api,apscehd_api,ipvs_api,
                       account_api, redis_api)

**Comment by welliamcao** [comment]
怎么可能，你是不是改了代码目录结构

**Comment by suyh1988** [comment]
抱歉我看错了
