### ISSUE TITLE
新建文档报"找不到路径"

### ISSUE THREAD

**Issue by nondevops** [welliamcao/OpsManage#277]
部署环境:
mac
mysql5.7
其他依赖组件与requirement一致;
python virtual虚拟环境部署

问题描述:
新建文档报"找不到路径"

操作过程:
点击新建文档菜单后下一跳报404
请求链接为http://127.0.0.1:88/noperm/?next=/wiki/add/

相关证据:
![image](https://user-images.githubusercontent.com/12181410/87500459-0b464900-c68f-11ea-9bea-3c4747350e6e.png)

辅助性排查:
The current path, noperm/, didn't match any of these.

**Comment by nondevops** [comment]
@welliamcao 可以帮忙看看这个问题吗?谢谢

**Comment by welliamcao** [comment]
不是提示你没权限吗？

**Comment by nondevops** [comment]
> 不是提示你没权限吗？

这不应该是403那个页面吗
