### ISSUE TITLE
deploy script  脚本工具 提示sudo： 需要密码

### ISSUE THREAD

**Issue by l4fu** [welliamcao/OpsManage#284]
如果 资产那里配置root账户密码就可以脚本部署成功，配置普通账户密码和sudo，提示sudo： 需要密码 （password is requred）  是否配置sudo密码都报这个错误。

**Comment by Robin5911** [comment]
运行剧本也一样，asset里面我已经写sudo密码了，but 报错
fatal: [xx.net]: FAILED! => {"_ansible_parsed": false, "msg": "MODULE FAILURE", "module_stdout": "sudo: a password is required\r\n", "module_stderr": "Shared connection to xx.net closed.\r\n", "rc": 1, "_ansible_verbose_override": true, "_ansible_no_log": false, "changed": false}

**Comment by gudan803** [comment]
运行模块工具也遇到同样的问题，“sudo: a password is required."

**Comment by welliamcao** [comment]
已修复。
