### ISSUE TITLE
修复beatBUG后,引发其他模块报错

### ISSUE THREAD

**Issue by nondevops** [welliamcao/OpsManage#285]
修复beatBUG后,引发其他模块报错
![image](https://user-images.githubusercontent.com/12181410/90850941-c310f980-e3a5-11ea-858e-40d0c863bead.png)

django降成原来版本该问题临时解决

**Comment by welliamcao** [comment]
fixed详见：https://github.com/welliamcao/OpsManage/commit/8a25ce43c00311c855a3319643d71e42e0a3daa3
