### ISSUE TITLE
opmanage v3 cmdb模块添加资产有个“使用组”字段不知道在那定义

### ISSUE THREAD

**Issue by flytor89** [welliamcao/OpsManage#286]
opmanage v3 cmdb模块添加资产有个“使用组”字段不知道在那定义

![image](https://user-images.githubusercontent.com/55431210/91163254-def70100-e6ff-11ea-9c5b-77874d1b70bf.png)

**Comment by welliamcao** [comment]
用户管理
![image](https://user-images.githubusercontent.com/5885314/91243765-4e5f0600-e77d-11ea-9b58-9301357f4610.png)

**Comment by flytor89** [comment]
收到，感谢！

**Comment by bobzhanggmail** [comment]
![1111](https://user-images.githubusercontent.com/9858448/91289926-8be78180-e7c5-11ea-874d-c0d9611dd27a.png)
 设置组后（选的下拉框第二个组）保存，提示成功，重新点编辑进来，还是显示第一个下拉选项

**Comment by welliamcao** [comment]
> ![1111](https://user-images.githubusercontent.com/9858448/91289926-8be78180-e7c5-11ea-874d-c0d9611dd27a.png)
> 设置组后（选的下拉框第二个组）保存，提示成功，重新点编辑进来，还是显示第一个下拉选项

我晚点修复一下

**Comment by welliamcao** [comment]
已修复
