### ISSUE TITLE
操作日志无法写入数据库

### ISSUE THREAD

**Issue by mission802** [welliamcao/OpsManage#29]
+ ansible运行模块后没有操作日志，查看数据库发现操作日志一直都是空的。

**Comment by welliamcao** [comment]
全局配置里面开启了日志记录功能了吗？

**Comment by mission802** [comment]
开启日志记录后，执行结果一直是：服务器正在处理，请稍后...   但在操作日志中可以看到已经执行成功。
![image](https://user-images.githubusercontent.com/6419682/30305549-08dc8654-97a6-11e7-802c-2a9c8330df23.png)

![image](https://user-images.githubusercontent.com/6419682/30305502-d292e5ac-97a5-11e7-8f6f-31edf7e80343.png)

**Comment by welliamcao** [comment]
你的redis是不是挂了，或者配置有问题？

**Comment by mission802** [comment]
👍 redis配置问题，运行在protected模式了
