### ISSUE TITLE
【建议】希望提供官方docker镜像

### ISSUE THREAD

**Issue by mailbyms** [welliamcao/OpsManage#297]
一个初始化脚本（设置环境变量、账号密码、生成所需目录 等）
一个 docker-compose.yml 脚本
docker hub 上提供官方镜像

这样就不会有太多部署的 issue 了

**Comment by welliamcao** [comment]
好的，谢谢，你的意见

**Comment by suishaojian** [comment]
同求docker版本。感谢。

**Comment by xmlgrg** [comment]
你可以自己制作一个呀   
https://github.com/welliamcao/OpsManage/wiki/Docker%E6%9E%84%E5%BB%BAOpsManage

**Comment by welliamcao** [comment]
docker pull welliamcao/ops:base

**Comment by mailbyms** [comment]
OK
