### ISSUE TITLE
安装依赖报错

### ISSUE THREAD

**Issue by xb4876** [welliamcao/OpsManage#300]
安装Twisted==18.9.0抛异常
环境：阿里云 centos7  python3.8  
命令：pip3 install -i  Twisted
错误：`ERROR: Could not find a version that satisfies the requirement Twisted==18.9.0
ERROR: No matching distribution found for Twisted==18.9.0`

**Comment by welliamcao** [comment]
源码下载这个，然后安装

**Comment by rayshen3** [comment]
这么多组件和依赖，docker化不香吗？    现在要装那么多东西
