### ISSUE TITLE
资产列表执行资产更新，报错更新失败

### ISSUE THREAD

**Issue by adil0518** [welliamcao/OpsManage#337]
各位大佬新年好，麻烦帮忙看下哪里配置出问题了，资产列表执行资产更新，报错更新失败：
2022-02-07 10:46:23 [ERROR] runserver.py[line:154] HTTP POST /assets/modf/6/ 500 [0.01, 172.16.203.234:64452]

**Comment by scwen** [comment]
Ubuntu 22.04 LTS   CentOS Stream release 8 这些新的系统主机就是更新失败，我也遇到一样的问题不知道怎么玩了。CentOS Linux release 7不会有这个问题

**Comment by welliamcao** [comment]
> Ubuntu 22.04 LTS CentOS Stream release 8 这些新的系统主机就是更新失败，我也遇到一样的问题不知道怎么玩了。CentOS Linux release 7不会有这个问题

已经优化了，这个原因是因为Ubuntu 22.04 LTS / CentOS Stream release 8系统自带的python版本过高，ansible执行setup模块会提示ImportError: cannot import name 'Mapping‘错误导致无法获取数据，解决方案是将默认的python版本降到3.10以下就可以了。
