### ISSUE TITLE
目标服务器在哪儿录入啊

### ISSUE THREAD

**Issue by yang-wj** [welliamcao/OpsManage#365]
![image](https://user-images.githubusercontent.com/50098975/216910451-83214408-c070-4b0c-b792-d136c9f3b289.png)
我真是太笨了

**Comment by welliamcao** [comment]
![image](https://user-images.githubusercontent.com/5885314/224522048-3dcd83dc-3fab-4689-81a0-44b9691c1222.png)

**Comment by yang-wj** [comment]
你的邮件已收到，谢谢！
