### ISSUE TITLE
css 未载入，因为它的 MIME 类型 "text/html" 不是 "text/css"。

### ISSUE THREAD

**Issue by cfzzx666** [welliamcao/OpsManage#367]
样式表单 http://192.168.56.72:8000/login/?next=/static/font-awesome/css/font-awesome.min.css 未载入，因为它的 MIME 类型 "text/html" 不是 "text/css"。 [login](http://192.168.56.72:8000/login/?next=/)
样式表单 http://192.168.56.72:8000/login/?next=/static/nprogress/nprogress.css 未载入，因为它的 MIME 类型 "text/html" 不是 "text/css"。 [login](http://192.168.56.72:8000/login/?next=/)
样式表单 http://192.168.56.72:8000/login/?next=/static/bootstrap/dist/css/bootstrap.min.css 未载入，因为它的 MIME 类型 "text/html" 不是 "text/css"。 [login](http://192.168.56.72:8000/login/?next=/)
样式表单 http://192.168.56.72:8000/login/?next=/static/css/custom.min.css 未载入，因为它的 MIME 类型 "text/html" 不是 "text/css"。

**Comment by welliamcao** [comment]
按照安装文档配置nginx
