### ISSUE TITLE
部署完毕后，系统web界面显示异常，浏览器开发工具显示各种Uncaught SyntaxError: Unexpected token '<' (at XX.js

### ISSUE THREAD

**Issue by bitsusu** [welliamcao/OpsManage#368]
部署完毕后，系统web界面显示异常，浏览器开发工具显示各种Uncaught SyntaxError: Unexpected token '<' (at XX.js

![image](https://user-images.githubusercontent.com/70457982/218270023-eb3d5085-811c-49ba-8921-d6a7b4ed848b.png)

**Comment by bitsusu** [comment]
下载包，在windows下，手工替换login.html里面的href为本地的static，显示正常。
在centos7.9部署机上，手动更改login.html和base.html里面的href，src为/mnt/OpsManage/...也不起作用

**Comment by staugur** [comment]
请提供部署环境（操作系统版本，python版本），，是否按照安装环境配置步骤安装的？  nginx配置文件看看

**Comment by bitsusu** [comment]
我把系统重装，且没有先执行 yum update -y，安装OpsManage成功。

**Comment by bitsusu** [comment]
请求加入QQ群
