### ISSUE TITLE
部署工具-资产配置-资产组变更，“修改主机”项出现多个undefined

### ISSUE THREAD

**Issue by gudan803** [welliamcao/OpsManage#369]
![image](https://user-images.githubusercontent.com/28525794/221562433-15f1c285-6f8f-47c8-aa04-03758c186535.png)

**Comment by welliamcao** [comment]
已修复，详见。
https://github.com/welliamcao/OpsManage/commit/9d44f4a98d3ee51f88adc6c3b075a106ea386f1d
