### ISSUE TITLE
回滚生产环境代码提示 项目部署失败，未选择目标服务器

### ISSUE THREAD

**Issue by vTNT** [welliamcao/OpsManage#37]
看了下 页面， 没有像部署的时候 显示可选的主机hosts

**Comment by welliamcao** [comment]
回滚的时候会直接读取数据库里面的目标主机配置，出现错误是不是，把目标主机取消了？

**Comment by vTNT** [comment]
没有取消， 我看了下 项目部署配置里面 目标主机都是有打勾的，  部署页面也有显示出目标主机，也可以部署正常，    就是回滚的时候， 回滚页面没有显示目标主机， 然后就报错了

**Comment by welliamcao** [comment]
确实是个bug，晚点修复。

**Comment by welliamcao** [comment]
@vTNT bug已经修复了

**Comment by vTNT** [comment]
另外在部署指定目标服务器 目录所属用户时， 如果该用户不存在，则部署不成功退出， 当编辑修改后， 重新部署就会提示 已锁， 然后再部署就会一直提示被锁 这时候需要进入redis 手动把 xx-locked这个key删掉 才可以重新部署

**Comment by vTNT** [comment]
需要手动删除 project.project_uuid+"-locked" 这个key

**Comment by welliamcao** [comment]
这个就是这样设计的

**Comment by vTNT** [comment]
ok
