### ISSUE TITLE
You have 39 unapplied migration(s)

### ISSUE THREAD

**Issue by yssky** [welliamcao/OpsManage#371]
[root@szcmdb OpsManage]# /usr/local/python3/bin/python3 manage.py createsuperuser

You have 39 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): apply, auth, cicd, contenttypes, databases, deploy, django_celery_beat, django_celery_results, navbar, orders, sched, sessions, wiki.
Run 'python manage.py migrate' to apply them.

**Comment by welliamcao** [comment]
> [root@szcmdb OpsManage]# /usr/local/python3/bin/python3 manage.py createsuperuser
> 
> You have 39 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): apply, auth, cicd, contenttypes, databases, deploy, django_celery_beat, django_celery_results, navbar, orders, sched, sessions, wiki. Run 'python manage.py migrate' to apply them.

Try run ```python3 manage.py migrate``` to apply them, before you run ```/usr/local/python3/bin/python3 manage.py createsuperuser```

**Comment by yssky** [comment]
已解决
