### ISSUE TITLE
在部署项目最后一步，执行命令，可否考虑以设定的用户执行？

### ISSUE THREAD

**Issue by xinschen** [welliamcao/OpsManage#39]
如图，能否考虑以程序账号去启动最后一步的执行命令，而非root账号？
![default](https://user-images.githubusercontent.com/26127685/31598454-5e01594e-b280-11e7-8859-5b8954f60c12.png)
![default](https://user-images.githubusercontent.com/26127685/31598457-5ea3ea60-b280-11e7-8aa7-bb146f9f6fa3.png)

**Comment by welliamcao** [comment]
把`touch /tmp/33/log.111` 改为 `su - testuser && touch /tmp/33/log.111` ?

**Comment by xinschen** [comment]
恩，目前就是这种方式来解决这个事情。提出来，是想能不能在功能点来解决这个问题，毕竟这种业务场景还是很常见的
