### ISSUE TITLE
权限没有做好吗

### ISSUE THREAD

**Issue by juforg** [welliamcao/OpsManage#4]
资产管理 和  发布 想让不同的人管  已经建了两个不同的组 ，对组分配了不同的 权限，但是资产管理组下的人 只有 基础配置有权限  其它的 还是没权限 ，即便对这个账户单独设置其它几个菜单权限也没用，
最终还是只有超级用户 能够访问所有的菜单

**Comment by welliamcao** [comment]
这个bug已经修复，OpsManage代码授权的时候写成Opsmanage导致权限不生效或者错误。
