### ISSUE TITLE
项目配置里面排除文件非空会部署失败

### ISSUE THREAD

**Issue by vTNT** [welliamcao/OpsManage#43]
由于exclude是从上面获取  格式如下：exclude = --exclude "{file}"   因此当赋值到synchronize模块参数的时候 不符合该模块语法  rsync_opts="{exclude}"
因此会提示 rsync语法错误

**Comment by welliamcao** [comment]
你的ansible跟rsync版本是多少的？我并没有复现出这个问题。

**Comment by vTNT** [comment]
ansible 版本2.3.2.0 
比如你项目配置里面 排除文件填入 .git
然后部署的时候会提示以下错误：--exclude ".git" : unknown option rsync error: syntax or usage error (code 1) at main.c(1572) [client=3.1.0]    
这个错误是由synchronize模块传入不合语法 引起的

**Comment by welliamcao** [comment]
rsync版本是多少的？

**Comment by vTNT** [comment]
rsync  version 3.1.0  protocol version 31

**Comment by vTNT** [comment]
- synchronize: src=/tmp/helloworld dest=/var/www/helloword rsync_opts=--exclude=.git
它的语法不是这样的吗？   那如果我们传进去的是 --exclude ".git"   那应该就不符合语法了把？

**Comment by vTNT** [comment]
同理 在运行模块页面中的sync选项， 如果模块参数是 --exclude=.git  而会报错
而如果是rsync_opts=--exclude=.git   那可以正常运行，

**Comment by welliamcao** [comment]
OpsManage代码是最新的吗？

**Comment by vTNT** [comment]
是啊，代码最新的
模块管理中 执行sync模块，默认模块参数是src=/root/a dest=/tmp/ compress=yes --exclude=.git，执行结果如下：
172.17.0.4 | FAILED! => {
    "_ansible_parsed": true,
    "_ansible_no_log": false,
    "failed": true,
    "msg": "Unsupported parameters for (synchronize) module: --exclude. Supported parameters include: _local_rsync_path,_substitute_controller,archive,checksum,compress,copy_links,delete,dest,dest_port,dirs,existing_only,group,links,mode,owner,partial,perms,private_key,recursive,rsync_opts,rsync_path,rsync_timeout,set_remote_user,src,ssh_args,times,verify_host"
}

**Comment by vTNT** [comment]
如果模块参数是src=/root/a dest=/tmp/ compress=yes --exclude=.git rsync_opts=--exclude=.git 那可以正常运行

**Comment by welliamcao** [comment]
OpsManage/views/deploy.py 336行，配置了rsync_opts

**Comment by vTNT** [comment]
= = 好吧 没遇到那就我自己环境问题吧。   exclude = --exclude "{file}" 因此当赋值到synchronize模块参数的时候 不符合该模块语法 rsync_opts="{exclude}"  问题其实是这个引起的， 需要重新构建传入的参数的。 我是这么修复的， 
`try:
    exclude = ''
    ansible_exclude_list = []
    for s in project.project_exclude.split(','):
        exclude = '--exclude "{file}"'.format(file=s.replace('\r\n', '').replace('\n', '').strip()) + ' ' + exclude
        exclude_str = '--exclude="{file}"'.format(file=s.replace('\r\n', '').replace('\n', '').strip())
        ansible_exclude_list.append(exclude_str)

 if ansible_exclude_list:
     ansible_exclude = ','.join(ansible_exclude_list)
     args = '''src={srcDir} dest={desDir} links=yes recursive=yes compress=yes delete=yes rsync_opts="{exclude}"'''.format(srcDir=softdir, desDir=project.dir, exclude=ansible_exclude)
 else:
      args = '''src={srcDir} dest={desDir} links=yes recursive=yes compress=yes delete=yes'''.format(srcDir=softdir, desDir=project.dir)
`

**Comment by vTNT** [comment]
https://github.com/hgz6536/opman-django/pull/6/files
这是我之后改的。  改完就正常了。
