### ISSUE TITLE
添加 部署之后执行的命令后部署就会失败

### ISSUE THREAD

**Issue by wodezz** [welliamcao/OpsManage#44]
如果填入部署之后执行的命令部署的时候就会失败，为空的时候 就部署成功。打印2次的dataList如下：
[{'msg': 'Ansible synchronize with src=/data/webserver/project/huimu/ dest=/data/game/ links=yes recursive=yes compress=yes delete=yes rsync_opts="--exclude ".git" " execute success.', 'ip': u'192.168.1.151', 'status': 'succeed'}]

命令为：/etc/init.d/tomcat restart
[{'msg': u'', 'ip': u'192.168.13.151', 'status': 'failed'}]
不清楚这是什么原因。。。有遇到过吗

**Comment by welliamcao** [comment]
如果有部署命令，需要手动把要部署的文件夹或者代码，复制到部署目录。

**Comment by wodezz** [comment]
不是编译命令是部署完后执行的命令

**Comment by wodezz** [comment]
![image](https://user-images.githubusercontent.com/17846193/32706912-4ebd6298-c85b-11e7-96a8-058a2b803ad7.png)
 是这里，我如果不填，就能部署成功。如果填了，就部署失败。dataList返回的是：
[{'msg': u'', 'ip': u'192.168.13.151', 'status': 'failed'}]

**Comment by welliamcao** [comment]
是不是你这个启动脚本没有返回状态？或者你可以试一下其他命令，比如ls -l /path/project

**Comment by wodezz** [comment]
用你说的这个命令也不行ANS.handle_model_data(ANS.get_model_result(), 'raw', module_args=project.project_remote_command) 返回的还是：
[{'msg': u'', 'ip': u'192.168.13.151', 'status': 'failed'}]

**Comment by wodezz** [comment]
用ls -l这样的命令也不行。还是通过不了

**Comment by wodezz** [comment]
启动脚本 就是正常的启动nginx的脚本/etc/init.d/nginx start

**Comment by welliamcao** [comment]
ansible版本是多少的？

**Comment by wodezz** [comment]
[root@localhost ~]# ansible --version
ansible 2.2.2.0

**Comment by welliamcao** [comment]
换成2.3+看看

**Comment by wodezz** [comment]
都是安照您写的requirements.txt文件里面版本要求安装的

**Comment by wodezz** [comment]
ok 我先试下

**Comment by welliamcao** [comment]
应用部署-运行模块-模块类型，选择shell，执行之后能返回数据吗？

**Comment by wodezz** [comment]
这块的功能还没用过呢，我现在在弄这个部署的功能

**Comment by wodezz** [comment]
![image](https://user-images.githubusercontent.com/17846193/32712304-ce018124-c87e-11e7-9ceb-16e395eaefd3.png)

**Comment by wodezz** [comment]
![image](https://user-images.githubusercontent.com/17846193/32712319-e0accbf8-c87e-11e7-9cfc-416ed829690f.png)

**Comment by wodezz** [comment]
我刚刚试了一下你说的这个功能 这2张截图是结果

**Comment by welliamcao** [comment]
执行失败了，主机不可达，秘钥不对？

**Comment by wodezz** [comment]
这2台机器都可以无密码登录呢

**Comment by wodezz** [comment]
[root@localhost ansible]# ansible all -m shell -a "uptime"             
192.168.13.151 | SUCCESS | rc=0 >>
 14:36:42 up 4 days, 14:54,  3 users,  load average: 0.07, 0.02, 0.00

192.168.13.152 | SUCCESS | rc=0 >>
 14:36:50 up 6 days, 12:54,  4 users,  load average: 0.00, 0.00, 0.00

**Comment by wodezz** [comment]
我在机器上面直接执行是没问题的，/etc/ansible/hosts文件内容如下：
[server]
192.168.13.151
192.168.13.152

**Comment by welliamcao** [comment]
/etc/ansible/ansible.cfg 里面有没有配置host_key_checking = False，秘钥文件是在root的默认目录吗？

**Comment by wodezz** [comment]
![image](https://user-images.githubusercontent.com/17846193/32712710-fe730a2e-c880-11e7-85ba-194142f9bdb3.png)

这次去部署能取到错误了  就是上面执行模块的时候的错误

**Comment by wodezz** [comment]
/etc/ansible/ansible.cfg 里面host_key_checking是注释掉的，没有使用。秘钥都在/root/.ssh下面

**Comment by wodezz** [comment]
换成2.3后发布也不能成功了

**Comment by wodezz** [comment]
晕 模块管理--模块执行又可以了。
服务器正在处理，请稍等。。。
[Start] Ansible Model: raw  ARGS:uptime

192.168.13.152 | SUCCESS | rc=0 >> 
 14:54:34 up 6 days, 13:12,  4 users,  load average: 0.00, 0.00, 0.00

192.168.13.151 | SUCCESS | rc=0 >> 
 14:54:26 up 4 days, 15:12,  3 users,  load average: 0.00, 0.00, 0.00

[Done] Ansible Done.
