### ISSUE TITLE
部署问题

### ISSUE THREAD

**Issue by wodezz** [welliamcao/OpsManage#45]
请问使用nginx+django有这样部署过吗

**Comment by xinschen** [comment]
只是nginx反向代理的话，简单使用proxy_pass设置下就可以的。

**Comment by xb4876** [comment]
我现在遇到个问题，nginx+uwsgi 启动项目  ansible  synchronize模块（rsync）无法调用的问题。
`ansible 2.2.2.0
Python 2.7.13
nginx-1.12.2
uwsgi 2.0.15
`
`[Start] Ansible 模块类型: synchronize  命令内容:src=/root/a dest=/tmp/ compress=yes
192.168.1.165 | FAILED! => {
    "_ansible_parsed": false, 
    "_ansible_no_log": false, 
    "module_stderr": "unable to load configuration from /root/.ansible/tmp/ansible-tmp-1511777799.47-133894082603415/synchronize.py\n", 
    "module_stdout": "", 
    "failed": true, 
    "msg": "MODULE FAILURE"
}`

**Comment by welliamcao** [comment]
不用nginx+uwsgi方式 synchronize能用吗？ @xb4876

**Comment by xb4876** [comment]
@welliamcao 
 python ./manage.py runserver 192.168.1.1:8001
这样启动  synchronize能用

**Comment by welliamcao** [comment]
@xb4876 你的机器上是否存在多Python环境？

**Comment by xb4876** [comment]
@welliamcao  是的  2.6  2.7   需要将2.6卸载？？

**Comment by welliamcao** [comment]
@xb4876 不需要卸载，可能是运行uwsgi时用的python版本不对

**Comment by xb4876** [comment]
@welliamcao  十分感谢  我试一试

**Comment by xb4876** [comment]
@welliamcao  我是pip安装到python2.7 路径下了  
uwsgi --ini wsgi.ini  这样运行uwsgi会有影响吗

**Comment by xb4876** [comment]
好 明白了
@welliamcao

**Comment by FrankDC** [comment]
这问题我也遇到过，请问怎么解决的，uwsgi是使用哪个python版本的pip安装的就属于哪个python版本

**Comment by xb4876** [comment]
@FrankDC 使用gunicorn替换uwsgi部署应用，ansible的synchronize模块可以使用。
使用gunicorn 代替uwsgi
gunicorn -w 4 -b 0.0.0.0:8003 curator.wsgi

**Comment by FrankDC** [comment]
好的，我先试下
谢谢您的回答

**Comment by yanyupan** [comment]
@xb4876 用gunicorn有没有测试过部署项目能正常吗？我这到编译时会卡住部署失败

**Comment by xb4876** [comment]
@yanyupan 正常啊 你是用什么编译的项目  我只是部署的java web项目  
ant -f /data/***/build.xml  用ant编译的
