### ISSUE TITLE
分支问题

### ISSUE THREAD

**Issue by wodezz** [welliamcao/OpsManage#47]
当我有一个master 一个Dev2个分支的时候 。我初始化后，点击"部署"后，在分支里面只看的到master分支，看不到dev分支。就是说初始化clone的时候 本地只有master分支，但是我要发布的是dev分支的东西。怎么弄

**Comment by welliamcao** [comment]
项目列表，有个切换分支的功能。

**Comment by welliamcao** [comment]
@wodezz 找到了吗？

**Comment by wodezz** [comment]
@welliamcao 看到了 谢谢！

**Comment by welliamcao** [comment]
@wodezz 你开的issues，处理完了，麻烦关闭一下。不然过一段时间，我会自动任务已经处理，再关掉:)
