### ISSUE TITLE
Django1.11.2

### ISSUE THREAD

**Issue by hgz6536** [welliamcao/OpsManage#5]
+----------------------------+
| Tables_in_opsmanage        |
|----------------------------|
| auth_group                 |
| auth_group_permissions     |
| auth_permission            |
| auth_user                  |
| auth_user_groups           |
| auth_user_user_permissions |
| celery_taskmeta            |
| celery_tasksetmeta         |
| django_admin_log           |
| django_content_type        |
| django_migrations          |
| django_session             |
| djcelery_crontabschedule   |
| djcelery_intervalschedule  |
| djcelery_periodictask      |
| djcelery_periodictasks     |
| djcelery_taskstate         |
| djcelery_workerstate       |
+----------------------------+
只有这些表被创建了，是为啥

**Comment by welliamcao** [comment]
换成MySQL5.1~5.6试一试。
