### ISSUE TITLE
celery

### ISSUE THREAD

**Issue by xb4876** [welliamcao/OpsManage#51]
调用tasks中的方法    recordAssets.delay(） delay方法没有执行
celery配置为
`
''' celery config '''
djcelery.setup_loader()
BROKER_URL = 'redis://192.168.1.***:6379/3'
CELERY_RESULT_BACKEND = 'djcelery.backends.database.DatabaseBackend'
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'pickle'
CELERY_ACCEPT_CONTENT = ['json', 'pickle']
CELERYBEAT_SCHEDULER = 'djcelery.schedulers.DatabaseScheduler'
CELERY_TASK_RESULT_EXPIRES = 60 * 60 * 24
CELERYD_MAX_TASKS_PER_CHILD = 40
CELERY_TRACK_STARTED = True
CELERY_TIMEZONE='Asia/Shanghai'
platforms.C_FORCE_ROOT = True`

**Comment by welliamcao** [comment]
celery版本与requirements.txt一致吗？

**Comment by xb4876** [comment]
都是3.1.20

**Comment by xb4876** [comment]
django应用启动之后，celery还需要单独启动吗？

**Comment by welliamcao** [comment]
要，看安装文档操作

**Comment by xb4876** [comment]
已经解决了  是celery启动不成功，配置全局变量export C_FORCE_ROOT="true"就可以了，主要原因是机器环境的问题
