### ISSUE TITLE
使用nginx+uwsgi部署项目  ansible synchronize模块无法执行

### ISSUE THREAD

**Issue by xb4876** [welliamcao/OpsManage#54]
之前提到过这个问题  python为2.7.13  ansible、uwsgi都装到/usr/local/lib/python2.7/site-packages下了。
`
[Start] Ansible 模块类型: synchronize  命令内容:src=/root/a dest=/tmp/ compress=yes
192.168.3.165 | FAILED! => {
    "_ansible_parsed": false, 
    "_ansible_no_log": false, 
    "module_stderr": "unable to load configuration from /root/.ansible/tmp/ansible-tmp-1511777799.47-133894082603415/synchronize.py\n", 
    "module_stdout": "", 
    "failed": true, 
    "msg": "MODULE FAILURE"
}
`

**Comment by wodezz** [comment]
是权限的问题吗

**Comment by xb4876** [comment]
@wodezz runserver启动没问题，其他模块没问题。

**Comment by kaelwang** [comment]
不是权限的问题，我也碰到了，跟执行用户没有关系，而且就只有这一个模块有这个问题，其它需要生成临时文件的都可以通过
