### ISSUE TITLE
ansible_args

### ISSUE THREAD

**Issue by xzGithu** [welliamcao/OpsManage#56]
apps_models.html与ansible.py中是不是有几处ansible_args错写成ansible_agrs了？
导致ansible运行模块时获取不到args

**Comment by mission802** [comment]
`apps_models.html`

![2017-12-15 17-49-14](https://user-images.githubusercontent.com/6419682/34036619-c6edf6d2-e1c0-11e7-834e-74b5b7f74d74.png)
![2017-12-15 17-49-42](https://user-images.githubusercontent.com/6419682/34036620-c719188a-e1c0-11e7-9847-d22e7ab0ca64.png)

`ansible.py`

![2017-12-15 17-51-52](https://user-images.githubusercontent.com/6419682/34036621-c744428a-e1c0-11e7-80b5-245c31d71784.png)

**Comment by welliamcao** [comment]
是写错了，但是不影响功能，下次更新将会修改成ansible_agrs。
