### ISSUE TITLE
更新apps_models.html文件

### ISSUE THREAD

**Issue by xzGithu** [welliamcao/OpsManage#58]
ansible 模块管理界面
模块类型选择“自定义”后，再次在模块类型选择“ping”，下面的“自定义模块“不会隐藏

apps_model.html添加
	   else if (value=="ping"){
		   document.getElementById("ansible_args").value="";
		   document.getElementById("custom_model").style.display = "none";
	   }

**Comment by welliamcao** [comment]
谢谢反馈，晚上回家看一下代码~

**Comment by welliamcao** [comment]
已更新代码
