### ISSUE TITLE
请问一下  我上传了剧本之后 在运维平台不能执行是什么原因？

### ISSUE THREAD

**Issue by z8772083** [welliamcao/OpsManage#63]
我上传了剧本之后 在你的平台执行之后，没有任何反应就结束了？

上传的剧本是否有格式要求？ 

这个剧本在我的服务器上是能正常执行的

![image](https://user-images.githubusercontent.com/18564603/34711107-05a831e8-f559-11e7-8318-9a87cf68096d.png)

**Comment by welliamcao** [comment]
![image](https://user-images.githubusercontent.com/5885314/34711192-650375da-f559-11e7-8673-1cd6f0994db4.png)
这个改了吗？

**Comment by z8772083** [comment]
按照你这样的写法可以了，多谢！！

**Comment by welliamcao** [comment]
@z8772083 如果你的剧本运行时间会超过3分钟，启动Django的时候可以配置一下--http_timeout 选项，不然会提示你503超时。

**Comment by z8772083** [comment]
@welliamcao  多谢提醒，另外我发现我的剧本列表里面是灰色 无法编辑了？ 我忘了做什么操作引起的了，请问是什么原因呢？
![image](https://user-images.githubusercontent.com/18564603/34714320-18f30ea2-f564-11e7-9fb1-61a9b1fa136a.png)

**Comment by welliamcao** [comment]
@z8772083 可能你把这个剧本的授权信息弄错了

**Comment by z8772083** [comment]
@welliamcao 可能是的，我再看看，3Q
