### ISSUE TITLE
任务调度不会用

### ISSUE THREAD

**Issue by shihuizhen** [welliamcao/OpsManage#65]
我用新版本的代码，任务调度不能用，不知道怎么配置任务要做什么事情。配置了任务在supervisor 启动的celery log 中，可以看到任务进来。但是不知道怎么让他真的做事儿。

**Comment by welliamcao** [comment]
![image](https://user-images.githubusercontent.com/5885314/34826234-bfbeb2c4-f710-11e7-8687-26fd8b65b80b.png)
上图参数说明：
1.OpsManage.tasks.AnsibleScripts表示执行ansible scripts类型的任务
2.OpsManage.tasks.AnsiblePlayBook表示执行ansible playbook类型的任务
3.传入脚本id，host表示目标主机（如果你的脚本或者剧本有绑定主机可以不填），logs表示将执行结果写入数据库。
希望能帮助到你:)

**Comment by shihuizhen** [comment]
收益匪浅，一直也闹不明白这个celery,通过学习你的代码，弄明白了好多。谢谢。

**Comment by shihuizhen** [comment]
centos 6.5 python 2.7.13  安装最新版本的paramiko, celery 计划任务可以提交到worker执行，但是ansible playbook 不生效，执行没有效果。paramiko==2.2.0 
cffi==1.11.3 ansible==2.3.2.0 正常
下面是pip freeze 的内容

amqp==1.4.9
ansible==2.3.2.0
anyjson==0.3.3
asgi-redis==1.4.3
asgiref==1.1.2
asn1crypto==0.24.0
attrs==17.4.0
autobahn==17.10.1
Automat==0.6.0
bcrypt==3.1.4
billiard==3.3.0.23
celery==3.1.20
celery-with-redis==3.0
cffi==1.11.3
channels==1.1.7
constantly==15.1.0
cryptography==2.1.4
daphne==1.4.2
DBUtils==1.2
Django==1.11.7
django-celery==3.2.2
djangorestframework==3.5.3
enum34==1.1.6
hyperlink==17.3.1
idna==2.6
incremental==17.5.0
ipaddress==1.0.19
Jinja2==2.10
kombu==3.0.37
MarkupSafe==1.0
meld3==1.0.2
msgpack==0.5.0
msgpack-python==0.5.0
MySQL-python==1.2.5
paramiko==2.2.0
pyasn1==0.4.2
pyasn1-modules==0.2.1
pycparser==2.18
pycrypto==2.6.1
PyNaCl==1.2.1
pyOpenSSL==17.5.0
pytz==2017.3
PyYAML==3.12
redis==2.10.6
service-identity==17.0.0
six==1.11.0
supervisor==3.3.3
Twisted==17.9.0
txaio==2.8.2
xlrd==1.1.0
zope.interface==4.4.3

**Comment by welliamcao** [comment]
@shihuizhen 提供一下task的参数？

**Comment by shihuizhen** [comment]
函数OpsManage.tasks.AnsiblePlayBook
参数{ "playbook_id": "1", "hosts": [ "10.1.52.214", "10.1.52.215" ], "logs": 1 }

playbook 内容
- hosts: "{{host}}"
  gather_facts: no
  tasks:
    - name: echo
      shell: echo '1111' >> /tmp/test.log

**Comment by shihuizhen** [comment]
现在还有一个问题，任务调度的运行日志里面没有东西。

**Comment by welliamcao** [comment]
启动supervisord时，这一步做了吗？
![image](https://user-images.githubusercontent.com/5885314/34969926-436848ee-faac-11e7-951a-8f0c9a3e4681.png)

**Comment by shihuizhen** [comment]
做了。写到环境变量了。不写的时候执行结果：
"{'status': {}, 'skipped': {}, 'ok': {}, 'changed': {}, 'failed': {}, 'unreachable': {}}"
写了的话如果版本不对报这个错误。
fatal: [10.1.52.214]: FAILED! => {"msg": "imported module support code does not exist at /opt/env/opsmanage/lib/python2.7/site-packages/ansible/module_utils/six/__init__.py", "failed": true}
针对我的情况，重装了好几个版本的ansible 和 paramiko cffi 最后找到了合适的版本

**Comment by welliamcao** [comment]
要配置export PYTHONOPTIMIZE=1  Celery才能让ansible 工作正常

**Comment by welliamcao** [comment]
@shihuizhen `fatal: [10.1.52.214]: FAILED! => {"msg": "imported module support code does not exist at /opt/env/opsmanage/lib/python2.7/site-packages/ansible/module_utils/six/init.py", "failed": true}`这个看着像是你的服务器上存在多个版本的python环境，你要确认Celery Worker在调用ansible的时候，加载正确的版本.

**Comment by shihuizhen** [comment]
我用的是vitrualenv。所有都是装在这里面的。
