### ISSUE TITLE
关于webssh在Channel使用上的错误

### ISSUE THREAD

**Issue by YoLoveLife** [welliamcao/OpsManage#66]
在我的理解中OpsManage在[consumers.py](https://github.com/welliamcao/OpsManage/blob/master/OpsManage/consumers.py)的处理稍微有一些问题。用户的操作会缓慢。

**你选择在def connect中查询资产中的连接信息 而在def receive中建立ssh连接来操作具体用户提交上来的命令。**

但是实际上用户的多次提交命令都是进入def receive()中的，这会出现一个问题：就是用户每一次执行命令其实是新创建了一个ssh连接，通过debug就可以看到每一次用户执行命令后sshClient的实例也就是self.ssh这个变量一直在更换内存地址，也就是每次命令都new一个新的SSH连接实例。这样会造成用户操作ssh的时间其实包含了连接ssh的时间。
正确的做法应该是在def connect中直接将self.ssh连接，由于websocket会一直保留，在receive中直接调用self.ssh来执行命令并且返回结果。
这样在用户操作的生命周期中 只需要建立一次ssh连接；而你现在的做法是每一次操作都进行一次ssh连接。
**不知道我对你的代码理解有没有差错。希望关注一下。**
@welliamcao

**Comment by welliamcao** [comment]
@YoLoveLife 我看了代码，receive()会判断传递过来的数据是否包含服务器id，才会创建ssh连接，并不会敲一个命令就会建立连接，不过你提的在connect时建立ssh连接是很好的建议:）

**Comment by YoLoveLife** [comment]
我又看了一下代码，的确在receive()一开始就会进行数值的判断。
我是觉得一个WS的建立应该一开始就基于正确的信息，也就是页面发起的WS在connect()时就判断是否正确，receive()和JS的send()只负责传递数据而不要包含太多的业务逻辑。如果在数据交互的过程中涉及过多的逻辑判断和数据查询会使得效率降低。
另外我有一个理解不知道对不对：服务器是可以通过receive()函数返回{‘accept’:'False'}这样的字典来终止这个WS，而用户则需要重新去connect()一个新的WS来完成他所需要的功能。

**Comment by welliamcao** [comment]
@YoLoveLife receive()里面包含太多判断确实影响效率，之前有考虑做日志审计，不过现在在开发SQL审核功能，没时间做了。现在没有保持Session的功能，所以每次都会创建新的WS连接。

**Comment by YoLoveLife** [comment]
我还有一个问题。你的系统中使用Channel以及xterm.js可以时间 shell中的Tab键的功能吗 @welliamcao

**Comment by welliamcao** [comment]
@YoLoveLife 支持
