### ISSUE TITLE
资产添加失败

### ISSUE THREAD

**Issue by suntao098** [welliamcao/OpsManage#7]
添加资产显示错误，更新本地数据库依旧如此。【资产编号重复，添加资产失败~】资产编号貌似有问题

**Comment by welliamcao** [comment]
【资产编号重复，添加资产失败~】这个错误，可能是资产输入的内容跟数据库表字段要求不一致导致的。
@suntao098 检查一下你输入的内容。

**Comment by suntao098** [comment]
不知道，添加总是报400请求错误

**Comment by welliamcao** [comment]
添加的时候，用谷歌浏览器--右击页面检查--Network(网络)，查看接口返回的数据？

**Comment by suntao098** [comment]
![qq 20170714093736](https://user-images.githubusercontent.com/25994115/28194631-227f78da-6878-11e7-9000-19495731364d.png)

**Comment by welliamcao** [comment]
点击server/ 看一下response返回的内容。
