### ISSUE TITLE
新安装完成 资产查询报错

### ISSUE THREAD

**Issue by dudochen** [welliamcao/OpsManage#79]
OperationalError at /assets_search/
(1055, "Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'opsmanage.opsmanage_assets.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by")

**Comment by jumping** [comment]
MySQL mode 配置改下，报错里面写了不兼容。要  sql_mode里面去掉only_full_group_by。

**Comment by dudochen** [comment]
谢谢，明白了
