### ISSUE TITLE
为什么我一打开资产列表就报错

### ISSUE THREAD

**Issue by zhangsulei** [welliamcao/OpsManage#80]
(1054, "Unknown column 'opsmanage_networkcard_assets.ip' in 'field list'")

**Comment by welliamcao** [comment]
```
mysql> use opsmanage;
mysql> desc opsmanage_networkcard_assets;
```
看一下这个表是不是少了一个ip字段

**Comment by welliamcao** [comment]
方法一：
```1.删除migrations这个目录
2.清空数据库 drop database opsmanage
3.创建数据库 
mysql> create database opsmanage;
mysql> grant all privileges on opsmanage.* to root@'%' identified by 'password';
3.重新生成数据表
python manage.py makemigrations OpsManage
python manage.py migrate
python manage.py createsuperuser
```
方法二：
进入数据库，把opsmanage_networkcard_assets这个表按照models.py要求添加一个ip列

**Comment by zhangsulei** [comment]
Did you rename networkcard_assets.address to networkcard_assets.ip (a GenericIPAddressField)? [y/N] y
You are trying to add a non-nullable field 'order_file' to sql_audit_order without a default; we can't do that (the database needs something to populate existing rows).
Please select a fix:
 1) Provide a one-off default now (will be set on all existing rows with a null value for this column)
 2) Quit, and let me add a default in models.py       我加了一个ip列还是报错

**Comment by welliamcao** [comment]
你把migrations 这个目录删除掉，再重新建表
