### ISSUE TITLE
SVN初始化失败

### ISSUE THREAD

**Issue by openbytes** [welliamcao/OpsManage#82]
svn 点击初始化失败.经测试, svn 服务器正常,用户密码正确.可以再其他机器正常检出代码和文件.报错内容如下:
初始化失败，失败原因： ----------------------------------------------------------------------- 注意! 你的密码，对于认证域: CollabNet Subversion Repository 只能明文保存在磁盘上! 如果可能的话，请考虑配置你的系统，让 Subversion 可以保存加密后的密码。请参阅文档以获得详细信息。 你可以通过在“/root/.subversion/servers”中设置选项“store-plaintext-passwords”为“yes”或“no”， 来避免再次出现此警告。 ----------------------------------------------------------------------- 保存未加密的密码(yes/no)?svn: E070014: Unable to connect to a repository at URL 'http://172.10.3.110:3434/svn/ansible_playbook' svn: E070014: 无法读取标准输入: End of file found

**Comment by welliamcao** [comment]
要先解决svn操作时提示输入账户密码的问题

**Comment by openbytes** [comment]
这个是代码层的还是 svn 那边的问题?大佬

**Comment by welliamcao** [comment]
你到源代码目录执行svn命令操作，看看会不会提示用户名跟密码

**Comment by openbytes** [comment]
去目录执行 checkout命令,会提示输入用户名和密码,检出之后,再去平台点击初始化 svn, 就正常,不会报错.
![wechatimg50](https://user-images.githubusercontent.com/34796404/38651295-05bfef54-3e33-11e8-8018-d201f66bc8e2.jpeg)
![image](https://user-images.githubusercontent.com/34796404/38651337-430d9a3c-3e33-11e8-8599-aa1b823a13fc.png)

**Comment by openbytes** [comment]
大佬,早上好!
使用 svn 部署代码的时候,提示部署失败.后台日志没报错信息.无法定位问题所在.能帮忙看看是因为配置的问题嘛?
![image](https://user-images.githubusercontent.com/34796404/38712362-afe9be86-3efd-11e8-8242-f763de0b1141.png)

![wechatimg52](https://user-images.githubusercontent.com/34796404/38712426-2e01dfe2-3efe-11e8-9b88-cfbd54d60a78.jpeg)

**Comment by welliamcao** [comment]
看一下接口返回状态是不是503，检查一下redis是否正常

**Comment by openbytes** [comment]
redis 正常.接口状态码500.
![image](https://user-images.githubusercontent.com/34796404/38715369-5465953e-3f0d-11e8-9c7b-1386efb556ca.png)

**Comment by welliamcao** [comment]
提供一下这个接口返回错误信息
