### ISSUE TITLE
使用inception审核语句时，上传语句有中文注释，审核提交程序出现bug

### ISSUE THREAD

**Issue by a5546868001** [welliamcao/OpsManage#83]
审核提交后页面出现 
DjangoUnicodeDecodeError at /db/sql/order/list/1/

'utf8' codec can't decode bytes in position 998-999: unexpected end of data. You passed in "-- \xe6\x96\x87\xe6\xa1\xa3\xe5\xaf\x86\xe7\xba\xa7\xef\xbc\x9a\xe5\x85\xac\xe5\x8f\xb8\xe5\x86\x85\xe9\x83\xa8A\r\n-- \xe6\xa0\xb8\xe6\x9f\xa5\xe8\xa1\xa8\xe6\xb7\xbb\xe5\x8a\xa01\xe4\xb8\xaa\xe5\xad\x97\xe6\xae\xb5\r\n

**Comment by welliamcao** [comment]
确保数据库跟inception都配置了utf8

**Comment by a5546868001** [comment]
都是utf8，在线编写中输入中文注释是可以执行的，只有上传附件里面的中文会报错，而且对于没有中文注释的上传附件点击审核提交之后，显示未授权，请问在哪里授权可以执行

**Comment by welliamcao** [comment]
`1.显示未授权，请问在哪里授权可以执行`
你向谁申请的授权，那个账户才可以授权
`2.而且SQL在提交之前好像只进行了语法审核，没有进行语义审核，导致对有些不存在的表执行操作也能提交`
在线SQL还是上传SQL文本会出现？

**Comment by welliamcao** [comment]
**1.我用被申请的账户登录，发现那条SQL也显示未授权，没有找到授权位置**
这个能提供截图吗？
**上传文本会出现**
这个其实就是调用mysql导入命令的，只能人工审核文件内容

**Comment by a5546868001** [comment]
我用其他用户提交的SQL选择dt账户为执行人，但是我用dt账户登录的时候也提示未授权，无法执行
![default](https://user-images.githubusercontent.com/26135288/38907459-6942fed0-42ee-11e8-9b0d-e27ac64edc85.png)

**Comment by welliamcao** [comment]
授权不在这个页面，在sql工单列表里面。

**Comment by a5546868001** [comment]
这个按钮么 点击没有反应
![default](https://user-images.githubusercontent.com/26135288/38907896-7a8dc6f0-42f0-11e8-84c9-0a8f9b1308c7.png)

**Comment by welliamcao** [comment]
什么浏览器？

**Comment by a5546868001** [comment]
火狐

**Comment by welliamcao** [comment]
换成谷歌浏览器试一试，火狐js代码不兼容，还没找到解决办法

**Comment by a5546868001** [comment]
可以了 感谢大神

**Comment by a5546868001** [comment]
上传脚本的时候 能不能上传到输入框内，提交审核的时候跟手动输入SQL一样 进入inception相应规则审核，现在点这个按钮好像就一直卡在这个界面 但是我审核SQL是能提交过去的。

![default](https://user-images.githubusercontent.com/26135288/38908183-ab39d234-42f1-11e8-9a56-1bb425e7788f.png)

**Comment by a5546868001** [comment]
如果能点一下上传 传到在线编辑SQL的那个文本框里面，然后在提交是不是可以解决审核的问题，把文本的内容全部放到文本框里面 不要直接审核文本内容

**Comment by welliamcao** [comment]
哪还不如把文本的sql粘贴到在线编辑的SQL里面
