### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by Toyouth** [welliamcao/OpsManage#86]
执行python manage.py makemigrations OpsManage后
数据库的属性会变成

![qq 20180413205446](https://user-images.githubusercontent.com/26453661/38736015-310e9c02-3f5d-11e8-9478-9472b0f1bfd2.png)

初始化的数据？号显示“？？？？？”

**Comment by Toyouth** [comment]
![qq 20180413205735](https://user-images.githubusercontent.com/26453661/38736048-52809b56-3f5d-11e8-86dc-abf99ec47ce9.png)
数据库都设置过，并重启了

**Comment by Toyouth** [comment]
![qq 20180413210100](https://user-images.githubusercontent.com/26453661/38736181-d2156a2c-3f5d-11e8-97f6-a715533970db.png)

**Comment by Toyouth** [comment]
![qq 20180413213155](https://user-images.githubusercontent.com/26453661/38737536-25fd5010-3f62-11e8-92a3-58e3b00d1952.png)
初始化的时候报错了，导致建表不全，这种情况如何解决啊---

**Comment by welliamcao** [comment]
你创建数据库的时候，字符集不是utf8的吧，你现在删掉数据库重新生成表结构

**Comment by Toyouth** [comment]
重新创建就可以了，但是建表的时候，还会报错，导致 表结构不全

**Comment by welliamcao** [comment]
你把migrations这个目录删除掉，这个缓存文件导致的，下个版本再修复。

**Comment by Toyouth** [comment]
解决了，谢谢老哥，问下有么有详细的使用文档啊

**Comment by welliamcao** [comment]
暂时还没写，还在更新功能，使用平台要先配置资产管理那一块，资产管理是其他功能的基础

**Comment by Toyouth** [comment]
但是项目维护上了，这是环境问题吗

**Comment by welliamcao** [comment]
celery有问题？

**Comment by Toyouth** [comment]
没问题
![qq 20180418193244](https://user-images.githubusercontent.com/26453661/38929583-631cc1d4-433f-11e8-9007-040e6398536b.png)

**Comment by Toyouth** [comment]
![qq 20180418195605](https://user-images.githubusercontent.com/26453661/38930465-9001e4f6-4342-11e8-8c91-29cc1544fd64.png)

**Comment by Toyouth** [comment]
老哥，是啥原因啊，我是按照安装文档一步一步来的...除了Redis是之前装过的
redis-server (pid 22198) 正在运行...

**Comment by welliamcao** [comment]
celery明显有问题

**Comment by welliamcao** [comment]
看celery的日志

**Comment by Toyouth** [comment]
ERROR/MainProcess] consumer: Cannot connect to redis://192.168.99.244:6379/4: .

Redis配置问题，改好了

资产更新主体信息成功，但是更新内存信息失败
提示：数据更新失败，系统可能不支持，未能获取数据

**Comment by welliamcao** [comment]
https://github.com/welliamcao/OpsManage/issues/69
看这个

**Comment by Toyouth** [comment]
ansible 2.4.4.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible/my_modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible-2.4.4.0-py2.7.egg/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Apr 12 2018, 22:04:48) [GCC 4.4.7 20120313 (Red Hat 4.4.7-18)]

配置还是更新失败

**Comment by Toyouth** [comment]
192.168.99.244 | FAILED! => {
    "failed": true, 
    "msg": "module (crawHw) is missing interpreter line"
}

**Comment by Toyouth** [comment]
MegaCli 没有安装

**Comment by Toyouth** [comment]
![qq 20180419104227](https://user-images.githubusercontent.com/26453661/38968509-60dc32e0-43be-11e8-9bbb-df726db92d74.png)
还是报错，脚本里两个方法都在shell里执行了，没问题啊

**Comment by welliamcao** [comment]
你的ansible怎么是2.4.4的不应该是2.3的吗？

**Comment by Toyouth** [comment]
![Uploading QQ截图20180419140658.png…]()
版本换成2.3还是不行

**Comment by welliamcao** [comment]
webserver这一组的机器上都安装了dmidecode，MegaCli64吗？

**Comment by Toyouth** [comment]
OpsManage 就装在webserver这台服务上，文件中dmidecode，MegaCli64指令单独执行都是可以的

**Comment by welliamcao** [comment]
看一下ansible配置文件
