### ISSUE TITLE
requirements.txt缺少django-ckeditor和Pillow，导致第八步执行报错

### ISSUE THREAD

**Issue by yinjiayi** [welliamcao/OpsManage#87]
添加就可以了django-ckeditor，Pillow

**Comment by welliamcao** [comment]
Pillow指定了版本，django-ckeditor可以不用安装，只用了ckeditor前端js，css，后端model忘记取消了%>_<%

**Comment by yinjiayi** [comment]
运维知识 新建文档和文档列表报错
![QQ截图20180415164854.png](https://i.loli.net/2018/04/15/5ad3124488f99.png)

**Comment by welliamcao** [comment]
python manage.py makemigrations wiki 生成wiki项目所需表，之前忘记更新安装文档

**Comment by mission802** [comment]
是不是还缺少了elfinder

**Comment by welliamcao** [comment]
@mission802  elfinder集成在里面的
