### ISSUE TITLE
uwsgi问题

### ISSUE THREAD

**Issue by wodezz** [welliamcao/OpsManage#88]
我把项目放到线上服务器后，使用uwsgi启动项目后，以前能发布程序，现在发布失败了。报错如下：

找不出是哪里的问题，请求解决！

**Comment by wodezz** [comment]
[{'msg': u'MODULE FAILURE', 'ip': u'192.168.13.152', 'status': 'failed'}]

**Comment by wodezz** [comment]
使用django自动启动发布没有问题，使用uwsgi后 就是发布不成功

**Comment by wodezz** [comment]
使用django自带的启动后发布成功，信息如下：
[{'msg': u'Ansible synchronize with src=/data/webserver/project/jn_mj_test/jn_mj/ dest=/data/game/jn_mj/ links=yes recursive=yes compress=yes delete=yes rsync_opts="--exclude=".git" " execute success.', 'ip': u'192.168.13.152', 'status': 'succeed'}]

**Comment by welliamcao** [comment]
看上去是没加载到正确的python环境

**Comment by wodezz** [comment]
这个问题我要怎么排查呢 ，现在我是无从下手
