### ISSUE TITLE
使用ansible 执行playbook ,时间长了报失败

### ISSUE THREAD

**Issue by qingduyu** [welliamcao/OpsManage#91]
playbook 执行初始化脚本，需要时间很长的yum 安装，结果就报错提示失败，其实后台还在执行，我手动执行过是成功的，平台上哪里有时间设置，可以延长超时时间
![default](https://user-images.githubusercontent.com/10934057/39745815-f894b9ce-52da-11e8-84f9-29b9f9819894.png)

**Comment by welliamcao** [comment]
https://github.com/welliamcao/OpsManage/issues/64 
另外可以加QQ群：627248919了解一下。
