### ISSUE TITLE
v2.2.1上传剧本是不是有异常

### ISSUE THREAD

**Issue by Lancger** [welliamcao/OpsManage#95]
![default](https://user-images.githubusercontent.com/16274422/40033748-5a2a9586-582c-11e8-9732-b2c58d10619a.png)

**Comment by welliamcao** [comment]
是不是浏览器不兼容

**Comment by welliamcao** [comment]
上传剧本目标主机如果选择自定义模式，目标主机没办法写入数据库，这个问题是因为bootstrap-multiselect这个组件对submit方法支持不友好，我暂时没找到解决办法所以先去掉了，改用bootstrap原生的多选组件。
